// Code generated by ent, DO NOT EDIT.

package playlist

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the playlist type in the database.
	Label = "playlist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldFriendlyToken holds the string denoting the friendly_token field in the database.
	FieldFriendlyToken = "friendly_token"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAddDate holds the string denoting the add_date field in the database.
	FieldAddDate = "add_date"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the playlist in the database.
	Table = "files_playlist"
	// UserTable is the table that holds the user relation/edge. The primary key declared below.
	UserTable = "user_playlists"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users_user"
)

// Columns holds all SQL columns for playlist fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldFriendlyToken,
	FieldUID,
	FieldUserID,
	FieldAddDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "files_playlist"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"media_playlist_playlist",
}

var (
	// UserPrimaryKey and UserColumn2 are the table columns denoting the
	// primary key for the user relation (M2M).
	UserPrimaryKey = []string{"user_id", "playlist_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// FriendlyTokenValidator is a validator for the "friendly_token" field. It is called by the builders before save.
	FriendlyTokenValidator func(string) error
	// DefaultAddDate holds the default value on creation for the "add_date" field.
	DefaultAddDate func() time.Time
)

// OrderOption defines the ordering options for the Playlist queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByFriendlyToken orders the results by the friendly_token field.
func ByFriendlyToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFriendlyToken, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAddDate orders the results by the add_date field.
func ByAddDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddDate, opts...).ToFunc()
}

// ByUserCount orders the results by user count.
func ByUserCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserStep(), opts...)
	}
}

// ByUser orders the results by user terms.
func ByUser(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, UserTable, UserPrimaryKey...),
	)
}
