// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "slug", Type: field.TypeString, Unique: true, Nullable: true, Size: 128},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "thumbnail", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "listings_thumbnail", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "icon", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "color", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "sequence", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeInt, Default: 1},
		{Name: "media_count", Type: field.TypeInt, Default: 0},
		{Name: "is_global", Type: field.TypeBool, Default: false},
		{Name: "is_rbac_category", Type: field.TypeBool, Default: false},
		{Name: "identity_provider", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
		{Name: "media_category_category", Type: field.TypeInt, Nullable: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "categories_categories_children",
				Columns:    []*schema.Column{CategoriesColumns[16]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "categories_files_media_category_category",
				Columns:    []*schema.Column{CategoriesColumns[17]},
				RefColumns: []*schema.Column{FilesMediaCategoryColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "categories_users_user_categories",
				Columns:    []*schema.Column{CategoriesColumns[18]},
				RefColumns: []*schema.Column{UsersUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "category_name",
				Unique:  false,
				Columns: []*schema.Column{CategoriesColumns[1]},
			},
			{
				Name:    "category_slug",
				Unique:  false,
				Columns: []*schema.Column{CategoriesColumns[2]},
			},
			{
				Name:    "category_parent_id",
				Unique:  false,
				Columns: []*schema.Column{CategoriesColumns[16]},
			},
			{
				Name:    "category_status",
				Unique:  false,
				Columns: []*schema.Column{CategoriesColumns[9]},
			},
			{
				Name:    "category_is_global",
				Unique:  false,
				Columns: []*schema.Column{CategoriesColumns[11]},
			},
		},
	}
	// UsersChannelColumns holds the columns for the "users_channel" table.
	UsersChannelColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 90},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "friendly_token", Type: field.TypeString, Unique: true, Size: 12},
		{Name: "banner_logo", Type: field.TypeString, Size: 500},
		{Name: "add_date", Type: field.TypeTime},
		{Name: "user_channels", Type: field.TypeInt},
	}
	// UsersChannelTable holds the schema information for the "users_channel" table.
	UsersChannelTable = &schema.Table{
		Name:       "users_channel",
		Columns:    UsersChannelColumns,
		PrimaryKey: []*schema.Column{UsersChannelColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_channel_users_user_channels",
				Columns:    []*schema.Column{UsersChannelColumns[6]},
				RefColumns: []*schema.Column{UsersUserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_title",
				Unique:  false,
				Columns: []*schema.Column{UsersChannelColumns[1]},
			},
			{
				Name:    "channel_friendly_token",
				Unique:  false,
				Columns: []*schema.Column{UsersChannelColumns[3]},
			},
			{
				Name:    "channel_add_date",
				Unique:  false,
				Columns: []*schema.Column{UsersChannelColumns[5]},
			},
		},
	}
	// FilesCommentColumns holds the columns for the "files_comment" table.
	FilesCommentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
		{Name: "uid", Type: field.TypeUUID, Unique: true},
		{Name: "add_date", Type: field.TypeTime},
		{Name: "media_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// FilesCommentTable holds the schema information for the "files_comment" table.
	FilesCommentTable = &schema.Table{
		Name:       "files_comment",
		Columns:    FilesCommentColumns,
		PrimaryKey: []*schema.Column{FilesCommentColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "comment_media_id",
				Unique:  false,
				Columns: []*schema.Column{FilesCommentColumns[4]},
			},
			{
				Name:    "comment_user_id",
				Unique:  false,
				Columns: []*schema.Column{FilesCommentColumns[5]},
			},
			{
				Name:    "comment_add_date",
				Unique:  false,
				Columns: []*schema.Column{FilesCommentColumns[3]},
			},
		},
	}
	// EncodeProfilesColumns holds the columns for the "encode_profiles" table.
	EncodeProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "extension", Type: field.TypeString, Size: 20, Default: "mp4"},
		{Name: "resolution", Type: field.TypeString, Size: 20},
		{Name: "video_codec", Type: field.TypeString, Size: 50, Default: "h264"},
		{Name: "video_bitrate", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "audio_codec", Type: field.TypeString, Size: 50, Default: "aac"},
		{Name: "audio_bitrate", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "bento_parameters", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// EncodeProfilesTable holds the schema information for the "encode_profiles" table.
	EncodeProfilesTable = &schema.Table{
		Name:       "encode_profiles",
		Columns:    EncodeProfilesColumns,
		PrimaryKey: []*schema.Column{EncodeProfilesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "encodeprofile_name",
				Unique:  false,
				Columns: []*schema.Column{EncodeProfilesColumns[1]},
			},
			{
				Name:    "encodeprofile_is_active",
				Unique:  false,
				Columns: []*schema.Column{EncodeProfilesColumns[10]},
			},
		},
	}
	// EncodingTasksColumns holds the columns for the "encoding_tasks" table.
	EncodingTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "pending"},
		{Name: "progress", Type: field.TypeInt, Default: 0},
		{Name: "output_path", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "profile_id", Type: field.TypeInt},
		{Name: "media_id", Type: field.TypeInt},
	}
	// EncodingTasksTable holds the schema information for the "encoding_tasks" table.
	EncodingTasksTable = &schema.Table{
		Name:       "encoding_tasks",
		Columns:    EncodingTasksColumns,
		PrimaryKey: []*schema.Column{EncodingTasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "encoding_tasks_encode_profiles_tasks",
				Columns:    []*schema.Column{EncodingTasksColumns[7]},
				RefColumns: []*schema.Column{EncodeProfilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "encoding_tasks_media_tasks",
				Columns:    []*schema.Column{EncodingTasksColumns[8]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "encodingtask_media_id",
				Unique:  false,
				Columns: []*schema.Column{EncodingTasksColumns[8]},
			},
			{
				Name:    "encodingtask_status",
				Unique:  false,
				Columns: []*schema.Column{EncodingTasksColumns[1]},
			},
			{
				Name:    "encodingtask_created_at",
				Unique:  false,
				Columns: []*schema.Column{EncodingTasksColumns[5]},
			},
		},
	}
	// FilesFavoriteColumns holds the columns for the "files_favorite" table.
	FilesFavoriteColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "media_favorites", Type: field.TypeInt, Nullable: true},
		{Name: "user_favorites", Type: field.TypeInt, Nullable: true},
	}
	// FilesFavoriteTable holds the schema information for the "files_favorite" table.
	FilesFavoriteTable = &schema.Table{
		Name:       "files_favorite",
		Columns:    FilesFavoriteColumns,
		PrimaryKey: []*schema.Column{FilesFavoriteColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "files_favorite_media_favorites",
				Columns:    []*schema.Column{FilesFavoriteColumns[2]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "files_favorite_users_user_favorites",
				Columns:    []*schema.Column{FilesFavoriteColumns[3]},
				RefColumns: []*schema.Column{UsersUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// FilesLikeColumns holds the columns for the "files_like" table.
	FilesLikeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "media_likes", Type: field.TypeInt, Nullable: true},
		{Name: "user_likes", Type: field.TypeInt, Nullable: true},
	}
	// FilesLikeTable holds the schema information for the "files_like" table.
	FilesLikeTable = &schema.Table{
		Name:       "files_like",
		Columns:    FilesLikeColumns,
		PrimaryKey: []*schema.Column{FilesLikeColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "files_like_media_likes",
				Columns:    []*schema.Column{FilesLikeColumns[2]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "files_like_users_user_likes",
				Columns:    []*schema.Column{FilesLikeColumns[3]},
				RefColumns: []*schema.Column{UsersUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "friendly_token", Type: field.TypeString, Unique: true, Nullable: true, Size: 150},
		{Name: "uuid", Type: field.TypeString, Unique: true, Nullable: true, Size: 36},
		{Name: "type", Type: field.TypeString, Size: 20, Default: "video"},
		{Name: "url", Type: field.TypeString, Size: 512},
		{Name: "hls_file", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "thumbnail", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "poster", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "preview_file_path", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "duration", Type: field.TypeInt, Default: 0},
		{Name: "size", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "width", Type: field.TypeInt, Default: 0},
		{Name: "height", Type: field.TypeInt, Default: 0},
		{Name: "mime_type", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "md5sum", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "extension", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "privacy", Type: field.TypeInt, Default: 1},
		{Name: "encoding_status", Type: field.TypeString, Size: 20, Default: "pending"},
		{Name: "state", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "view_count", Type: field.TypeInt64, Default: 0},
		{Name: "like_count", Type: field.TypeInt64, Default: 0},
		{Name: "dislike_count", Type: field.TypeInt64, Default: 0},
		{Name: "comment_count", Type: field.TypeInt64, Default: 0},
		{Name: "favorite_count", Type: field.TypeInt64, Default: 0},
		{Name: "download_count", Type: field.TypeInt64, Default: 0},
		{Name: "allow_download", Type: field.TypeBool, Default: true},
		{Name: "enable_comments", Type: field.TypeBool, Default: true},
		{Name: "featured", Type: field.TypeBool, Default: false},
		{Name: "is_reviewed", Type: field.TypeBool, Default: true},
		{Name: "reported_times", Type: field.TypeInt, Default: 0},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "category_media", Type: field.TypeInt, Nullable: true},
		{Name: "media_category_media", Type: field.TypeInt, Nullable: true},
		{Name: "media_playlist_media", Type: field.TypeInt, Nullable: true},
		{Name: "media_tag_media", Type: field.TypeInt, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_categories_media",
				Columns:    []*schema.Column{MediaColumns[36]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "media_files_media_category_media",
				Columns:    []*schema.Column{MediaColumns[37]},
				RefColumns: []*schema.Column{FilesMediaCategoryColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "media_files_playlistmedia_media",
				Columns:    []*schema.Column{MediaColumns[38]},
				RefColumns: []*schema.Column{FilesPlaylistmediaColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "media_files_media_tags_media",
				Columns:    []*schema.Column{MediaColumns[39]},
				RefColumns: []*schema.Column{FilesMediaTagsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "media_users_user_media",
				Columns:    []*schema.Column{MediaColumns[40]},
				RefColumns: []*schema.Column{UsersUserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "media_uuid",
				Unique:  true,
				Columns: []*schema.Column{MediaColumns[4]},
			},
			{
				Name:    "media_friendly_token",
				Unique:  true,
				Columns: []*schema.Column{MediaColumns[3]},
			},
			{
				Name:    "media_title",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[1]},
			},
			{
				Name:    "media_type",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[5]},
			},
			{
				Name:    "media_state",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[20]},
			},
			{
				Name:    "media_encoding_status",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[19]},
			},
			{
				Name:    "media_featured",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[29]},
			},
			{
				Name:    "media_view_count",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[21]},
			},
			{
				Name:    "media_created_at",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[34]},
			},
			{
				Name:    "media_user_id",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[40]},
			},
		},
	}
	// FilesMediaCategoryColumns holds the columns for the "files_media_category" table.
	FilesMediaCategoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// FilesMediaCategoryTable holds the schema information for the "files_media_category" table.
	FilesMediaCategoryTable = &schema.Table{
		Name:       "files_media_category",
		Columns:    FilesMediaCategoryColumns,
		PrimaryKey: []*schema.Column{FilesMediaCategoryColumns[0]},
	}
	// FilesPlaylistmediaColumns holds the columns for the "files_playlistmedia" table.
	FilesPlaylistmediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ordering", Type: field.TypeInt, Default: 1},
		{Name: "action_date", Type: field.TypeTime},
		{Name: "media_playlists", Type: field.TypeInt, Nullable: true},
	}
	// FilesPlaylistmediaTable holds the schema information for the "files_playlistmedia" table.
	FilesPlaylistmediaTable = &schema.Table{
		Name:       "files_playlistmedia",
		Columns:    FilesPlaylistmediaColumns,
		PrimaryKey: []*schema.Column{FilesPlaylistmediaColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "files_playlistmedia_media_playlists",
				Columns:    []*schema.Column{FilesPlaylistmediaColumns[3]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// FilesMediaTagsColumns holds the columns for the "files_media_tags" table.
	FilesMediaTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "media_tags_rel", Type: field.TypeInt, Nullable: true},
	}
	// FilesMediaTagsTable holds the schema information for the "files_media_tags" table.
	FilesMediaTagsTable = &schema.Table{
		Name:       "files_media_tags",
		Columns:    FilesMediaTagsColumns,
		PrimaryKey: []*schema.Column{FilesMediaTagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "files_media_tags_media_tags_rel",
				Columns:    []*schema.Column{FilesMediaTagsColumns[1]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersNotificationColumns holds the columns for the "users_notification" table.
	UsersNotificationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "action", Type: field.TypeString, Size: 30},
		{Name: "notify", Type: field.TypeBool, Default: false},
		{Name: "method", Type: field.TypeString, Size: 20, Default: "email"},
		{Name: "user_id", Type: field.TypeInt},
	}
	// UsersNotificationTable holds the schema information for the "users_notification" table.
	UsersNotificationTable = &schema.Table{
		Name:       "users_notification",
		Columns:    UsersNotificationColumns,
		PrimaryKey: []*schema.Column{UsersNotificationColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notification_user_id",
				Unique:  false,
				Columns: []*schema.Column{UsersNotificationColumns[4]},
			},
		},
	}
	// FilesPlaylistColumns holds the columns for the "files_playlist" table.
	FilesPlaylistColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "friendly_token", Type: field.TypeString, Unique: true, Size: 12},
		{Name: "uid", Type: field.TypeUUID, Unique: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "add_date", Type: field.TypeTime},
		{Name: "media_playlist_playlist", Type: field.TypeInt, Nullable: true},
	}
	// FilesPlaylistTable holds the schema information for the "files_playlist" table.
	FilesPlaylistTable = &schema.Table{
		Name:       "files_playlist",
		Columns:    FilesPlaylistColumns,
		PrimaryKey: []*schema.Column{FilesPlaylistColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "files_playlist_files_playlistmedia_playlist",
				Columns:    []*schema.Column{FilesPlaylistColumns[7]},
				RefColumns: []*schema.Column{FilesPlaylistmediaColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "playlist_title",
				Unique:  false,
				Columns: []*schema.Column{FilesPlaylistColumns[1]},
			},
			{
				Name:    "playlist_friendly_token",
				Unique:  false,
				Columns: []*schema.Column{FilesPlaylistColumns[3]},
			},
			{
				Name:    "playlist_user_id",
				Unique:  false,
				Columns: []*schema.Column{FilesPlaylistColumns[5]},
			},
			{
				Name:    "playlist_add_date",
				Unique:  false,
				Columns: []*schema.Column{FilesPlaylistColumns[6]},
			},
		},
	}
	// FilesTagColumns holds the columns for the "files_tag" table.
	FilesTagColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "media_count", Type: field.TypeInt, Default: 0},
		{Name: "listings_thumbnail", Type: field.TypeString, Size: 400},
		{Name: "media_tag_tag", Type: field.TypeInt, Nullable: true},
	}
	// FilesTagTable holds the schema information for the "files_tag" table.
	FilesTagTable = &schema.Table{
		Name:       "files_tag",
		Columns:    FilesTagColumns,
		PrimaryKey: []*schema.Column{FilesTagColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "files_tag_files_media_tags_tag",
				Columns:    []*schema.Column{FilesTagColumns[4]},
				RefColumns: []*schema.Column{FilesMediaTagsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tag_title",
				Unique:  false,
				Columns: []*schema.Column{FilesTagColumns[1]},
			},
			{
				Name:    "tag_media_count",
				Unique:  false,
				Columns: []*schema.Column{FilesTagColumns[2]},
			},
		},
	}
	// UploadSessionsColumns holds the columns for the "upload_sessions" table.
	UploadSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "upload_id", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "filename", Type: field.TypeString, Size: 255},
		{Name: "file_size", Type: field.TypeInt64},
		{Name: "content_type", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "total_parts", Type: field.TypeInt},
		{Name: "chunk_size", Type: field.TypeInt, Default: 2097152},
		{Name: "uploaded_size", Type: field.TypeInt64, Default: 0},
		{Name: "title", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "category_id", Type: field.TypeInt64, Nullable: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "pending"},
		{Name: "parts", Type: field.TypeJSON, Nullable: true},
		{Name: "sha256", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "storage_path", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "temp_dir", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UploadSessionsTable holds the schema information for the "upload_sessions" table.
	UploadSessionsTable = &schema.Table{
		Name:       "upload_sessions",
		Columns:    UploadSessionsColumns,
		PrimaryKey: []*schema.Column{UploadSessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "uploadsession_upload_id",
				Unique:  true,
				Columns: []*schema.Column{UploadSessionsColumns[1]},
			},
			{
				Name:    "uploadsession_user_id",
				Unique:  false,
				Columns: []*schema.Column{UploadSessionsColumns[12]},
			},
			{
				Name:    "uploadsession_status",
				Unique:  false,
				Columns: []*schema.Column{UploadSessionsColumns[13]},
			},
			{
				Name:    "uploadsession_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UploadSessionsColumns[18]},
			},
		},
	}
	// UsersUserColumns holds the columns for the "users_user" table.
	UsersUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 150},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 254},
		{Name: "password", Type: field.TypeString, Size: 256},
		{Name: "name", Type: field.TypeString, Size: 250, SchemaType: map[string]string{"postgres": "VARCHAR(250)"}},
		{Name: "first_name", Type: field.TypeString, Nullable: true, Size: 150},
		{Name: "last_name", Type: field.TypeString, Nullable: true, Size: 150},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_staff", Type: field.TypeBool, Default: false},
		{Name: "is_superuser", Type: field.TypeBool, Default: false},
		{Name: "is_approved", Type: field.TypeBool, Nullable: true},
		{Name: "is_featured", Type: field.TypeBool, Default: false},
		{Name: "advanced_user", Type: field.TypeBool, Default: false},
		{Name: "is_editor", Type: field.TypeBool, Default: false},
		{Name: "is_manager", Type: field.TypeBool, Default: false},
		{Name: "title", Type: field.TypeString, Nullable: true, Size: 250},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "logo", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "location", Type: field.TypeString, Nullable: true, Size: 250},
		{Name: "media_count", Type: field.TypeInt, Default: 0},
		{Name: "notification_on_comments", Type: field.TypeBool, Default: true},
		{Name: "allow_contact", Type: field.TypeBool, Default: false},
		{Name: "date_joined", Type: field.TypeTime},
		{Name: "date_added", Type: field.TypeTime},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
		{Name: "favorite_user", Type: field.TypeInt, Nullable: true},
		{Name: "like_user", Type: field.TypeInt, Nullable: true},
	}
	// UsersUserTable holds the schema information for the "users_user" table.
	UsersUserTable = &schema.Table{
		Name:       "users_user",
		Columns:    UsersUserColumns,
		PrimaryKey: []*schema.Column{UsersUserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_user_files_favorite_user",
				Columns:    []*schema.Column{UsersUserColumns[25]},
				RefColumns: []*schema.Column{FilesFavoriteColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "users_user_files_like_user",
				Columns:    []*schema.Column{UsersUserColumns[26]},
				RefColumns: []*schema.Column{FilesLikeColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  false,
				Columns: []*schema.Column{UsersUserColumns[1]},
			},
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersUserColumns[2]},
			},
			{
				Name:    "user_is_active",
				Unique:  false,
				Columns: []*schema.Column{UsersUserColumns[7]},
			},
			{
				Name:    "user_is_staff",
				Unique:  false,
				Columns: []*schema.Column{UsersUserColumns[8]},
			},
			{
				Name:    "user_date_added",
				Unique:  false,
				Columns: []*schema.Column{UsersUserColumns[23]},
			},
		},
	}
	// ChannelMediaColumns holds the columns for the "channel_media" table.
	ChannelMediaColumns = []*schema.Column{
		{Name: "channel_id", Type: field.TypeInt},
		{Name: "media_id", Type: field.TypeInt},
	}
	// ChannelMediaTable holds the schema information for the "channel_media" table.
	ChannelMediaTable = &schema.Table{
		Name:       "channel_media",
		Columns:    ChannelMediaColumns,
		PrimaryKey: []*schema.Column{ChannelMediaColumns[0], ChannelMediaColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_media_channel_id",
				Columns:    []*schema.Column{ChannelMediaColumns[0]},
				RefColumns: []*schema.Column{UsersChannelColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "channel_media_media_id",
				Columns:    []*schema.Column{ChannelMediaColumns[1]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// CommentRepliesColumns holds the columns for the "comment_replies" table.
	CommentRepliesColumns = []*schema.Column{
		{Name: "comment_id", Type: field.TypeInt},
		{Name: "reply_id", Type: field.TypeInt},
	}
	// CommentRepliesTable holds the schema information for the "comment_replies" table.
	CommentRepliesTable = &schema.Table{
		Name:       "comment_replies",
		Columns:    CommentRepliesColumns,
		PrimaryKey: []*schema.Column{CommentRepliesColumns[0], CommentRepliesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comment_replies_comment_id",
				Columns:    []*schema.Column{CommentRepliesColumns[0]},
				RefColumns: []*schema.Column{FilesCommentColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "comment_replies_reply_id",
				Columns:    []*schema.Column{CommentRepliesColumns[1]},
				RefColumns: []*schema.Column{FilesCommentColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// MediaCommentsColumns holds the columns for the "media_comments" table.
	MediaCommentsColumns = []*schema.Column{
		{Name: "media_id", Type: field.TypeInt},
		{Name: "comment_id", Type: field.TypeInt},
	}
	// MediaCommentsTable holds the schema information for the "media_comments" table.
	MediaCommentsTable = &schema.Table{
		Name:       "media_comments",
		Columns:    MediaCommentsColumns,
		PrimaryKey: []*schema.Column{MediaCommentsColumns[0], MediaCommentsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_comments_media_id",
				Columns:    []*schema.Column{MediaCommentsColumns[0]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "media_comments_comment_id",
				Columns:    []*schema.Column{MediaCommentsColumns[1]},
				RefColumns: []*schema.Column{FilesCommentColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserPlaylistsColumns holds the columns for the "user_playlists" table.
	UserPlaylistsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "playlist_id", Type: field.TypeInt},
	}
	// UserPlaylistsTable holds the schema information for the "user_playlists" table.
	UserPlaylistsTable = &schema.Table{
		Name:       "user_playlists",
		Columns:    UserPlaylistsColumns,
		PrimaryKey: []*schema.Column{UserPlaylistsColumns[0], UserPlaylistsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_playlists_user_id",
				Columns:    []*schema.Column{UserPlaylistsColumns[0]},
				RefColumns: []*schema.Column{UsersUserColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_playlists_playlist_id",
				Columns:    []*schema.Column{UserPlaylistsColumns[1]},
				RefColumns: []*schema.Column{FilesPlaylistColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserCommentsColumns holds the columns for the "user_comments" table.
	UserCommentsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "comment_id", Type: field.TypeInt},
	}
	// UserCommentsTable holds the schema information for the "user_comments" table.
	UserCommentsTable = &schema.Table{
		Name:       "user_comments",
		Columns:    UserCommentsColumns,
		PrimaryKey: []*schema.Column{UserCommentsColumns[0], UserCommentsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_comments_user_id",
				Columns:    []*schema.Column{UserCommentsColumns[0]},
				RefColumns: []*schema.Column{UsersUserColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_comments_comment_id",
				Columns:    []*schema.Column{UserCommentsColumns[1]},
				RefColumns: []*schema.Column{FilesCommentColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserNotificationsColumns holds the columns for the "user_notifications" table.
	UserNotificationsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "notification_id", Type: field.TypeInt},
	}
	// UserNotificationsTable holds the schema information for the "user_notifications" table.
	UserNotificationsTable = &schema.Table{
		Name:       "user_notifications",
		Columns:    UserNotificationsColumns,
		PrimaryKey: []*schema.Column{UserNotificationsColumns[0], UserNotificationsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_notifications_user_id",
				Columns:    []*schema.Column{UserNotificationsColumns[0]},
				RefColumns: []*schema.Column{UsersUserColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_notifications_notification_id",
				Columns:    []*schema.Column{UserNotificationsColumns[1]},
				RefColumns: []*schema.Column{UsersNotificationColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserTagsColumns holds the columns for the "user_tags" table.
	UserTagsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// UserTagsTable holds the schema information for the "user_tags" table.
	UserTagsTable = &schema.Table{
		Name:       "user_tags",
		Columns:    UserTagsColumns,
		PrimaryKey: []*schema.Column{UserTagsColumns[0], UserTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_tags_user_id",
				Columns:    []*schema.Column{UserTagsColumns[0]},
				RefColumns: []*schema.Column{UsersUserColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_tags_tag_id",
				Columns:    []*schema.Column{UserTagsColumns[1]},
				RefColumns: []*schema.Column{FilesTagColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		UsersChannelTable,
		FilesCommentTable,
		EncodeProfilesTable,
		EncodingTasksTable,
		FilesFavoriteTable,
		FilesLikeTable,
		MediaTable,
		FilesMediaCategoryTable,
		FilesPlaylistmediaTable,
		FilesMediaTagsTable,
		UsersNotificationTable,
		FilesPlaylistTable,
		FilesTagTable,
		UploadSessionsTable,
		UsersUserTable,
		ChannelMediaTable,
		CommentRepliesTable,
		MediaCommentsTable,
		UserPlaylistsTable,
		UserCommentsTable,
		UserNotificationsTable,
		UserTagsTable,
	}
)

func init() {
	CategoriesTable.ForeignKeys[0].RefTable = CategoriesTable
	CategoriesTable.ForeignKeys[1].RefTable = FilesMediaCategoryTable
	CategoriesTable.ForeignKeys[2].RefTable = UsersUserTable
	UsersChannelTable.ForeignKeys[0].RefTable = UsersUserTable
	UsersChannelTable.Annotation = &entsql.Annotation{
		Table: "users_channel",
	}
	FilesCommentTable.Annotation = &entsql.Annotation{
		Table: "files_comment",
	}
	EncodingTasksTable.ForeignKeys[0].RefTable = EncodeProfilesTable
	EncodingTasksTable.ForeignKeys[1].RefTable = MediaTable
	FilesFavoriteTable.ForeignKeys[0].RefTable = MediaTable
	FilesFavoriteTable.ForeignKeys[1].RefTable = UsersUserTable
	FilesFavoriteTable.Annotation = &entsql.Annotation{
		Table: "files_favorite",
	}
	FilesLikeTable.ForeignKeys[0].RefTable = MediaTable
	FilesLikeTable.ForeignKeys[1].RefTable = UsersUserTable
	FilesLikeTable.Annotation = &entsql.Annotation{
		Table: "files_like",
	}
	MediaTable.ForeignKeys[0].RefTable = CategoriesTable
	MediaTable.ForeignKeys[1].RefTable = FilesMediaCategoryTable
	MediaTable.ForeignKeys[2].RefTable = FilesPlaylistmediaTable
	MediaTable.ForeignKeys[3].RefTable = FilesMediaTagsTable
	MediaTable.ForeignKeys[4].RefTable = UsersUserTable
	FilesMediaCategoryTable.Annotation = &entsql.Annotation{
		Table: "files_media_category",
	}
	FilesPlaylistmediaTable.ForeignKeys[0].RefTable = MediaTable
	FilesPlaylistmediaTable.Annotation = &entsql.Annotation{
		Table: "files_playlistmedia",
	}
	FilesMediaTagsTable.ForeignKeys[0].RefTable = MediaTable
	FilesMediaTagsTable.Annotation = &entsql.Annotation{
		Table: "files_media_tags",
	}
	UsersNotificationTable.Annotation = &entsql.Annotation{
		Table: "users_notification",
	}
	FilesPlaylistTable.ForeignKeys[0].RefTable = FilesPlaylistmediaTable
	FilesPlaylistTable.Annotation = &entsql.Annotation{
		Table: "files_playlist",
	}
	FilesTagTable.ForeignKeys[0].RefTable = FilesMediaTagsTable
	FilesTagTable.Annotation = &entsql.Annotation{
		Table: "files_tag",
	}
	UsersUserTable.ForeignKeys[0].RefTable = FilesFavoriteTable
	UsersUserTable.ForeignKeys[1].RefTable = FilesLikeTable
	UsersUserTable.Annotation = &entsql.Annotation{
		Table: "users_user",
	}
	ChannelMediaTable.ForeignKeys[0].RefTable = UsersChannelTable
	ChannelMediaTable.ForeignKeys[1].RefTable = MediaTable
	CommentRepliesTable.ForeignKeys[0].RefTable = FilesCommentTable
	CommentRepliesTable.ForeignKeys[1].RefTable = FilesCommentTable
	MediaCommentsTable.ForeignKeys[0].RefTable = MediaTable
	MediaCommentsTable.ForeignKeys[1].RefTable = FilesCommentTable
	UserPlaylistsTable.ForeignKeys[0].RefTable = UsersUserTable
	UserPlaylistsTable.ForeignKeys[1].RefTable = FilesPlaylistTable
	UserCommentsTable.ForeignKeys[0].RefTable = UsersUserTable
	UserCommentsTable.ForeignKeys[1].RefTable = FilesCommentTable
	UserNotificationsTable.ForeignKeys[0].RefTable = UsersUserTable
	UserNotificationsTable.ForeignKeys[1].RefTable = UsersNotificationTable
	UserTagsTable.ForeignKeys[0].RefTable = UsersUserTable
	UserTagsTable.ForeignKeys[1].RefTable = FilesTagTable
}
