version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for workflow files in the .github/workflows directory
    directory: "/"
    schedule:
      interval: "weekly"