/*
 * Copyright (c) 2024 OrigAdmin. All rights reserved.
 */

package dal

import (
	"context"

	"origadmin/application/origstudio/internal/dal/entity"
	systemdto "origadmin/application/origstudio/internal/features/system/dto"
)

// SeedSettings seeds default settings into the database.
func SeedSettings(ctx context.Context, db *entity.Client) error {
	repo := NewSettingRepo(db)
	return repo.SeedDefaults(ctx, DefaultSettings())
}

// DefaultSettings returns the list of built-in default settings as DTOs.
// Moved from biz layer to break the import cycle between dal and biz packages.
func DefaultSettings() []*systemdto.SettingDTO {
	return []*systemdto.SettingDTO{
		{
			Key:           "site_name",
			Value:         "OrigStudio",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryGeneral,
			Description:   "Site name",
			FallbackValue: "OrigStudio",
			IsBuiltin:     true,
		},
		{
			Key:           "site_description",
			Value:         "A modern media CMS",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryGeneral,
			Description:   "Site description",
			FallbackValue: "A modern media CMS",
			IsBuiltin:     true,
		},
		{
			Key:           "base_url",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryGeneral,
			Description:   "Base URL of the site",
			FallbackValue: "",
			IsBuiltin:     true,
		},
		{
			Key:           "allow_registration",
			Value:         "true",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryGeneral,
			Description:   "Allow new user registration",
			FallbackValue: "true",
			IsBuiltin:     true,
		},
		{
			Key:           "allow_upload",
			Value:         "true",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Allow media upload",
			FallbackValue: "true",
			IsBuiltin:     true,
		},
		{
			Key:           "max_upload_size_video",
			Value:         "5368709120",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Max video upload size in bytes (5GB)",
			FallbackValue: "5368709120",
			IsBuiltin:     true,
		},
		{
			Key:           "max_upload_size_image",
			Value:         "52428800",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Max image upload size in bytes (50MB)",
			FallbackValue: "52428800",
			IsBuiltin:     true,
		},
		{
			Key:           "auto_approve",
			Value:         "false",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryAdvanced,
			Description:   "Auto approve submitted content",
			FallbackValue: "false",
			IsBuiltin:     true,
		},
		{
			Key:           "require_review",
			Value:         "true",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryAdvanced,
			Description:   "Require review before publishing",
			FallbackValue: "true",
			IsBuiltin:     true,
		},
		{
			Key:           "smtp_host",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryEmail,
			Description:   "SMTP server host",
			FallbackValue: "",
			IsBuiltin:     true,
		},
		{
			Key:           "smtp_port",
			Value:         "587",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryEmail,
			Description:   "SMTP server port",
			FallbackValue: "587",
			IsBuiltin:     true,
		},
		{
			Key:           "smtp_user",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryEmail,
			Description:   "SMTP username",
			FallbackValue: "",
			IsBuiltin:     true,
		},
		{
			Key:           "smtp_password",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryEmail,
			Description:   "SMTP password",
			FallbackValue: "",
			IsSensitive:   true,
			IsBuiltin:     true,
		},
		{
			Key:           "sprite_frame_interval",
			Value:         "10",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Sprite frame interval in seconds",
			FallbackValue: "10",
			IsBuiltin:     true,
		},
		{
			Key:           "sprite_columns",
			Value:         "5",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Number of columns in sprite image",
			FallbackValue: "5",
			IsBuiltin:     true,
		},
		{
			Key:           "sprite_frame_width",
			Value:         "160",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Width of each sprite frame in pixels",
			FallbackValue: "160",
			IsBuiltin:     true,
		},
		{
			Key:           "sprite_frame_height",
			Value:         "90",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Height of each sprite frame in pixels",
			FallbackValue: "90",
			IsBuiltin:     true,
		},
		{
			Key:           "sprite_max_frames",
			Value:         "100",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Maximum number of frames in sprite",
			FallbackValue: "100",
			IsBuiltin:     true,
		},
		{
			Key:           "thumbnail_quality",
			Value:         "2",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Thumbnail quality (1-31, lower is better)",
			FallbackValue: "2",
			IsBuiltin:     true,
		},
		{
			Key:           "thumbnail_resolution",
			Value:         "1280x720",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Thumbnail resolution",
			FallbackValue: "1280x720",
			IsBuiltin:     true,
		},
		{
			Key:           "thumbnail_position",
			Value:         "0.2",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Thumbnail position (0.0-1.0, percentage of video duration)",
			FallbackValue: "0.2",
			IsBuiltin:     true,
		},
		{
			Key:           "module_articles",
			Value:         "true",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryPortal,
			Description:   "Enable Articles content module",
			FallbackValue: "true",
			IsBuiltin:     true,
		},
		{
			Key:           "module_videos",
			Value:         "true",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryPortal,
			Description:   "Enable Videos content module",
			FallbackValue: "true",
			IsBuiltin:     true,
		},
		{
			Key:           "module_music",
			Value:         "false",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryPortal,
			Description:   "Enable Music content module",
			FallbackValue: "false",
			IsBuiltin:     true,
		},
		{
			Key:           "homepage_layout",
			Value:         "auto",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryPortal,
			Description:   "Homepage layout mode: auto|video|article|mixed|welcome",
			FallbackValue: "auto",
			IsBuiltin:     true,
		},
		{
			Key:           "storage_base_path",
			Value:         "./data/uploads",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Base path for media storage (subdirectories are auto-created)",
			FallbackValue: "./data/uploads",
			IsBuiltin:     true,
		},
		{
			Key:           "storage_type",
			Value:         "local",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Storage backend type: local, s3, hybrid",
			FallbackValue: "local",
			IsBuiltin:     true,
		},
		{
			Key:           "s3_endpoint",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "S3/MinIO endpoint URL",
			FallbackValue: "",
			IsBuiltin:     true,
		},
		{
			Key:           "s3_region",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "S3 region",
			FallbackValue: "",
			IsBuiltin:     true,
		},
		{
			Key:           "s3_bucket",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "S3 bucket name",
			FallbackValue: "",
			IsBuiltin:     true,
		},
		{
			Key:           "s3_access_key",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "S3 access key ID",
			FallbackValue: "",
			IsSensitive:   true,
			IsBuiltin:     true,
		},
		{
			Key:           "s3_secret_key",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "S3 secret access key",
			FallbackValue: "",
			IsSensitive:   true,
			IsBuiltin:     true,
		},
		{
			Key:           "s3_use_path_style",
			Value:         "false",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Use path-style S3 URLs (true for MinIO)",
			FallbackValue: "false",
			IsBuiltin:     true,
		},
		{
			Key:           "base_urls",
			Value:         `[""]`,
			Type:          systemdto.SettingTypeJSON,
			Category:      systemdto.SettingCategoryGeneral,
			Description:   "Allowed site URLs (JSON array, for CORS and validation)",
			FallbackValue: `[""]`,
			IsBuiltin:     true,
		},
		{
			Key:           "primary_url",
			Value:         "",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryGeneral,
			Description:   "Primary site URL for emails, SEO canonical URLs",
			FallbackValue: "",
			IsBuiltin:     true,
		},
		{
			Key:           "auto_transcode",
			Value:         "true",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Automatically transcode uploaded videos",
			FallbackValue: "true",
			IsBuiltin:     true,
		},
		{
			Key:           "transcode_method",
			Value:         "ffmpeg",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Transcode engine: ffmpeg",
			FallbackValue: "ffmpeg",
			IsBuiltin:     true,
		},
		{
			Key:           "allowed_video_formats",
			Value:         "mp4,webm,mkv,avi,mov",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Allowed video file extensions (comma-separated)",
			FallbackValue: "mp4,webm,mkv,avi,mov",
			IsBuiltin:     true,
		},
		{
			Key:           "allowed_image_formats",
			Value:         "jpg,png,gif,webp",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Allowed image file extensions (comma-separated)",
			FallbackValue: "jpg,png,gif,webp",
			IsBuiltin:     true,
		},
		{
			Key:           "max_video_duration",
			Value:         "7200",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryStorage,
			Description:   "Maximum video duration in seconds (0=unlimited)",
			FallbackValue: "7200",
			IsBuiltin:     true,
		},
		{
			Key:           "smtp_sender_name",
			Value:         "OrigStudio",
			Type:          systemdto.SettingTypeString,
			Category:      systemdto.SettingCategoryEmail,
			Description:   "Sender display name for outgoing emails",
			FallbackValue: "OrigStudio",
			IsBuiltin:     true,
		},
		{
			Key:           "smtp_use_tls",
			Value:         "true",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryEmail,
			Description:   "Use TLS for SMTP connection",
			FallbackValue: "true",
			IsBuiltin:     true,
		},
		{
			Key:           "min_password_length",
			Value:         "8",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryGeneral,
			Description:   "Minimum password length for registration",
			FallbackValue: "8",
			IsBuiltin:     true,
		},
		{
			Key:           "require_email_verification",
			Value:         "false",
			Type:          systemdto.SettingTypeBool,
			Category:      systemdto.SettingCategoryGeneral,
			Description:   "Require email verification after registration",
			FallbackValue: "false",
			IsBuiltin:     true,
		},
		{
			Key:           "api_rate_limit",
			Value:         "60",
			Type:          systemdto.SettingTypeInt,
			Category:      systemdto.SettingCategoryGeneral,
			Description:   "API rate limit (requests per minute per IP, 0=unlimited)",
			FallbackValue: "60",
			IsBuiltin:     true,
		},
	}
}
