// This file is generated by abgen, but you can edit it.
// More info: https://github.com/origadmin/abgen

package convpb

import (
	"strconv"

	"origadmin/application/origcms/internal/data/enums"
)

func ConvertEnumsEncodingTaskStatusToString(from enums.EncodingTaskStatus) string {
	return from.String()
}

func ConvertInt64ToString(from int64) string {
	return strconv.FormatInt(from, 10)
}

func ConvertStringToEnumsEncodingTaskStatus(from string) enums.EncodingTaskStatus {
	return enums.ParseEncodingTaskStatus(from)
}

func ConvertStringToInt64(from string) int64 {
	i, _ := strconv.ParseInt(from, 10, 64)
	return i
}
