// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"origadmin/application/origstudio/internal/dal/entity/promotionsubscription"
	"origadmin/application/origstudio/internal/dal/entity/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PromotionSubscriptionCreate is the builder for creating a PromotionSubscription entity.
type PromotionSubscriptionCreate struct {
	config
	mutation *PromotionSubscriptionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *PromotionSubscriptionCreate) SetUserID(v string) *PromotionSubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetChannelIds sets the "channel_ids" field.
func (_c *PromotionSubscriptionCreate) SetChannelIds(v []string) *PromotionSubscriptionCreate {
	_c.mutation.SetChannelIds(v)
	return _c
}

// SetTagIds sets the "tag_ids" field.
func (_c *PromotionSubscriptionCreate) SetTagIds(v []string) *PromotionSubscriptionCreate {
	_c.mutation.SetTagIds(v)
	return _c
}

// SetPlatforms sets the "platforms" field.
func (_c *PromotionSubscriptionCreate) SetPlatforms(v []string) *PromotionSubscriptionCreate {
	_c.mutation.SetPlatforms(v)
	return _c
}

// SetFrequency sets the "frequency" field.
func (_c *PromotionSubscriptionCreate) SetFrequency(v promotionsubscription.Frequency) *PromotionSubscriptionCreate {
	_c.mutation.SetFrequency(v)
	return _c
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_c *PromotionSubscriptionCreate) SetNillableFrequency(v *promotionsubscription.Frequency) *PromotionSubscriptionCreate {
	if v != nil {
		_c.SetFrequency(*v)
	}
	return _c
}

// SetQuietHours sets the "quiet_hours" field.
func (_c *PromotionSubscriptionCreate) SetQuietHours(v map[string]string) *PromotionSubscriptionCreate {
	_c.mutation.SetQuietHours(v)
	return _c
}

// SetDailyLimit sets the "daily_limit" field.
func (_c *PromotionSubscriptionCreate) SetDailyLimit(v int) *PromotionSubscriptionCreate {
	_c.mutation.SetDailyLimit(v)
	return _c
}

// SetNillableDailyLimit sets the "daily_limit" field if the given value is not nil.
func (_c *PromotionSubscriptionCreate) SetNillableDailyLimit(v *int) *PromotionSubscriptionCreate {
	if v != nil {
		_c.SetDailyLimit(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *PromotionSubscriptionCreate) SetIsActive(v bool) *PromotionSubscriptionCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *PromotionSubscriptionCreate) SetNillableIsActive(v *bool) *PromotionSubscriptionCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *PromotionSubscriptionCreate) SetTenantID(v string) *PromotionSubscriptionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *PromotionSubscriptionCreate) SetNillableTenantID(v *string) *PromotionSubscriptionCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *PromotionSubscriptionCreate) SetCreateTime(v time.Time) *PromotionSubscriptionCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *PromotionSubscriptionCreate) SetNillableCreateTime(v *time.Time) *PromotionSubscriptionCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *PromotionSubscriptionCreate) SetUpdateTime(v time.Time) *PromotionSubscriptionCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *PromotionSubscriptionCreate) SetNillableUpdateTime(v *time.Time) *PromotionSubscriptionCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromotionSubscriptionCreate) SetID(v string) *PromotionSubscriptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PromotionSubscriptionCreate) SetNillableID(v *string) *PromotionSubscriptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PromotionSubscriptionCreate) SetUser(v *User) *PromotionSubscriptionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PromotionSubscriptionMutation object of the builder.
func (_c *PromotionSubscriptionCreate) Mutation() *PromotionSubscriptionMutation {
	return _c.mutation
}

// Save creates the PromotionSubscription in the database.
func (_c *PromotionSubscriptionCreate) Save(ctx context.Context) (*PromotionSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionSubscriptionCreate) SaveX(ctx context.Context) *PromotionSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Frequency(); !ok {
		v := promotionsubscription.DefaultFrequency
		_c.mutation.SetFrequency(v)
	}
	if _, ok := _c.mutation.DailyLimit(); !ok {
		v := promotionsubscription.DefaultDailyLimit
		_c.mutation.SetDailyLimit(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := promotionsubscription.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := promotionsubscription.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := promotionsubscription.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := promotionsubscription.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := promotionsubscription.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionSubscriptionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`entity: missing required field "PromotionSubscription.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := promotionsubscription.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`entity: validator failed for field "PromotionSubscription.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Frequency(); !ok {
		return &ValidationError{Name: "frequency", err: errors.New(`entity: missing required field "PromotionSubscription.frequency"`)}
	}
	if v, ok := _c.mutation.Frequency(); ok {
		if err := promotionsubscription.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`entity: validator failed for field "PromotionSubscription.frequency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyLimit(); !ok {
		return &ValidationError{Name: "daily_limit", err: errors.New(`entity: missing required field "PromotionSubscription.daily_limit"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`entity: missing required field "PromotionSubscription.is_active"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`entity: missing required field "PromotionSubscription.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := promotionsubscription.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`entity: validator failed for field "PromotionSubscription.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`entity: missing required field "PromotionSubscription.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`entity: missing required field "PromotionSubscription.update_time"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := promotionsubscription.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`entity: validator failed for field "PromotionSubscription.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`entity: missing required edge "PromotionSubscription.user"`)}
	}
	return nil
}

func (_c *PromotionSubscriptionCreate) sqlSave(ctx context.Context) (*PromotionSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PromotionSubscription.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionSubscriptionCreate) createSpec() (*PromotionSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionsubscription.Table, sqlgraph.NewFieldSpec(promotionsubscription.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ChannelIds(); ok {
		_spec.SetField(promotionsubscription.FieldChannelIds, field.TypeJSON, value)
		_node.ChannelIds = value
	}
	if value, ok := _c.mutation.TagIds(); ok {
		_spec.SetField(promotionsubscription.FieldTagIds, field.TypeJSON, value)
		_node.TagIds = value
	}
	if value, ok := _c.mutation.Platforms(); ok {
		_spec.SetField(promotionsubscription.FieldPlatforms, field.TypeJSON, value)
		_node.Platforms = value
	}
	if value, ok := _c.mutation.Frequency(); ok {
		_spec.SetField(promotionsubscription.FieldFrequency, field.TypeEnum, value)
		_node.Frequency = value
	}
	if value, ok := _c.mutation.QuietHours(); ok {
		_spec.SetField(promotionsubscription.FieldQuietHours, field.TypeJSON, value)
		_node.QuietHours = value
	}
	if value, ok := _c.mutation.DailyLimit(); ok {
		_spec.SetField(promotionsubscription.FieldDailyLimit, field.TypeInt, value)
		_node.DailyLimit = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(promotionsubscription.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(promotionsubscription.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(promotionsubscription.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(promotionsubscription.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promotionsubscription.UserTable,
			Columns: []string{promotionsubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PromotionSubscriptionCreateBulk is the builder for creating many PromotionSubscription entities in bulk.
type PromotionSubscriptionCreateBulk struct {
	config
	err      error
	builders []*PromotionSubscriptionCreate
}

// Save creates the PromotionSubscription entities in the database.
func (_c *PromotionSubscriptionCreateBulk) Save(ctx context.Context) ([]*PromotionSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionSubscriptionCreateBulk) SaveX(ctx context.Context) []*PromotionSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
