// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"origadmin/application/origstudio/internal/dal/entity/order"
	"origadmin/application/origstudio/internal/dal/entity/refund"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RefundCreate is the builder for creating a Refund entity.
type RefundCreate struct {
	config
	mutation *RefundMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (_c *RefundCreate) SetAmount(v float64) *RefundCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *RefundCreate) SetReason(v string) *RefundCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *RefundCreate) SetNillableReason(v *string) *RefundCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RefundCreate) SetStatus(v refund.Status) *RefundCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RefundCreate) SetNillableStatus(v *refund.Status) *RefundCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *RefundCreate) SetOrderID(v string) *RefundCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *RefundCreate) SetCreateTime(v time.Time) *RefundCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *RefundCreate) SetNillableCreateTime(v *time.Time) *RefundCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *RefundCreate) SetUpdateTime(v time.Time) *RefundCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *RefundCreate) SetNillableUpdateTime(v *time.Time) *RefundCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RefundCreate) SetID(v string) *RefundCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RefundCreate) SetNillableID(v *string) *RefundCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrder sets the "order" edge to the Order entity.
func (_c *RefundCreate) SetOrder(v *Order) *RefundCreate {
	return _c.SetOrderID(v.ID)
}

// Mutation returns the RefundMutation object of the builder.
func (_c *RefundCreate) Mutation() *RefundMutation {
	return _c.mutation
}

// Save creates the Refund in the database.
func (_c *RefundCreate) Save(ctx context.Context) (*Refund, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RefundCreate) SaveX(ctx context.Context) *Refund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefundCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefundCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RefundCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := refund.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := refund.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := refund.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := refund.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RefundCreate) check() error {
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`entity: missing required field "Refund.amount"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := refund.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`entity: validator failed for field "Refund.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`entity: missing required field "Refund.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := refund.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`entity: validator failed for field "Refund.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`entity: missing required field "Refund.order_id"`)}
	}
	if v, ok := _c.mutation.OrderID(); ok {
		if err := refund.OrderIDValidator(v); err != nil {
			return &ValidationError{Name: "order_id", err: fmt.Errorf(`entity: validator failed for field "Refund.order_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`entity: missing required field "Refund.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`entity: missing required field "Refund.update_time"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := refund.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`entity: validator failed for field "Refund.id": %w`, err)}
		}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`entity: missing required edge "Refund.order"`)}
	}
	return nil
}

func (_c *RefundCreate) sqlSave(ctx context.Context) (*Refund, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Refund.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RefundCreate) createSpec() (*Refund, *sqlgraph.CreateSpec) {
	var (
		_node = &Refund{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(refund.Table, sqlgraph.NewFieldSpec(refund.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(refund.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(refund.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(refund.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(refund.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(refund.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refund.OrderTable,
			Columns: []string{refund.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RefundCreateBulk is the builder for creating many Refund entities in bulk.
type RefundCreateBulk struct {
	config
	err      error
	builders []*RefundCreate
}

// Save creates the Refund entities in the database.
func (_c *RefundCreateBulk) Save(ctx context.Context) ([]*Refund, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Refund, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefundMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RefundCreateBulk) SaveX(ctx context.Context) []*Refund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefundCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefundCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
