// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"origadmin/application/origstudio/internal/dal/entity/media"
	"origadmin/application/origstudio/internal/dal/entity/predicate"
	"origadmin/application/origstudio/internal/dal/entity/subtitle"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubtitleUpdate is the builder for updating Subtitle entities.
type SubtitleUpdate struct {
	config
	hooks     []Hook
	mutation  *SubtitleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SubtitleUpdate builder.
func (_u *SubtitleUpdate) Where(ps ...predicate.Subtitle) *SubtitleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMediaID sets the "media_id" field.
func (_u *SubtitleUpdate) SetMediaID(v string) *SubtitleUpdate {
	_u.mutation.SetMediaID(v)
	return _u
}

// SetNillableMediaID sets the "media_id" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableMediaID(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetMediaID(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *SubtitleUpdate) SetLanguage(v string) *SubtitleUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableLanguage(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *SubtitleUpdate) SetLabel(v string) *SubtitleUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableLabel(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *SubtitleUpdate) ClearLabel() *SubtitleUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *SubtitleUpdate) SetFileURL(v string) *SubtitleUpdate {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableFileURL(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// ClearFileURL clears the value of the "file_url" field.
func (_u *SubtitleUpdate) ClearFileURL() *SubtitleUpdate {
	_u.mutation.ClearFileURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubtitleUpdate) SetStatus(v string) *SubtitleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableStatus(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SubtitleUpdate) SetErrorMessage(v string) *SubtitleUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableErrorMessage(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SubtitleUpdate) ClearErrorMessage() *SubtitleUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *SubtitleUpdate) SetCreateTime(v time.Time) *SubtitleUpdate {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableCreateTime(v *time.Time) *SubtitleUpdate {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SubtitleUpdate) SetUpdateTime(v time.Time) *SubtitleUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableUpdateTime(v *time.Time) *SubtitleUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// SetMedia sets the "media" edge to the Media entity.
func (_u *SubtitleUpdate) SetMedia(v *Media) *SubtitleUpdate {
	return _u.SetMediaID(v.ID)
}

// Mutation returns the SubtitleMutation object of the builder.
func (_u *SubtitleUpdate) Mutation() *SubtitleMutation {
	return _u.mutation
}

// ClearMedia clears the "media" edge to the Media entity.
func (_u *SubtitleUpdate) ClearMedia() *SubtitleUpdate {
	_u.mutation.ClearMedia()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubtitleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubtitleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubtitleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubtitleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubtitleUpdate) check() error {
	if v, ok := _u.mutation.MediaID(); ok {
		if err := subtitle.MediaIDValidator(v); err != nil {
			return &ValidationError{Name: "media_id", err: fmt.Errorf(`entity: validator failed for field "Subtitle.media_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := subtitle.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`entity: validator failed for field "Subtitle.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := subtitle.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`entity: validator failed for field "Subtitle.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileURL(); ok {
		if err := subtitle.FileURLValidator(v); err != nil {
			return &ValidationError{Name: "file_url", err: fmt.Errorf(`entity: validator failed for field "Subtitle.file_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subtitle.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`entity: validator failed for field "Subtitle.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := subtitle.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`entity: validator failed for field "Subtitle.error_message": %w`, err)}
		}
	}
	if _u.mutation.MediaCleared() && len(_u.mutation.MediaIDs()) > 0 {
		return errors.New(`entity: clearing a required unique edge "Subtitle.media"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SubtitleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SubtitleUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SubtitleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subtitle.Table, subtitle.Columns, sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(subtitle.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(subtitle.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(subtitle.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(subtitle.FieldFileURL, field.TypeString, value)
	}
	if _u.mutation.FileURLCleared() {
		_spec.ClearField(subtitle.FieldFileURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subtitle.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(subtitle.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(subtitle.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(subtitle.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(subtitle.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtitle.MediaTable,
			Columns: []string{subtitle.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtitle.MediaTable,
			Columns: []string{subtitle.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subtitle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubtitleUpdateOne is the builder for updating a single Subtitle entity.
type SubtitleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SubtitleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetMediaID sets the "media_id" field.
func (_u *SubtitleUpdateOne) SetMediaID(v string) *SubtitleUpdateOne {
	_u.mutation.SetMediaID(v)
	return _u
}

// SetNillableMediaID sets the "media_id" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableMediaID(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetMediaID(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *SubtitleUpdateOne) SetLanguage(v string) *SubtitleUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableLanguage(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *SubtitleUpdateOne) SetLabel(v string) *SubtitleUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableLabel(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *SubtitleUpdateOne) ClearLabel() *SubtitleUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *SubtitleUpdateOne) SetFileURL(v string) *SubtitleUpdateOne {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableFileURL(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// ClearFileURL clears the value of the "file_url" field.
func (_u *SubtitleUpdateOne) ClearFileURL() *SubtitleUpdateOne {
	_u.mutation.ClearFileURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubtitleUpdateOne) SetStatus(v string) *SubtitleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableStatus(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SubtitleUpdateOne) SetErrorMessage(v string) *SubtitleUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableErrorMessage(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SubtitleUpdateOne) ClearErrorMessage() *SubtitleUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *SubtitleUpdateOne) SetCreateTime(v time.Time) *SubtitleUpdateOne {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableCreateTime(v *time.Time) *SubtitleUpdateOne {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SubtitleUpdateOne) SetUpdateTime(v time.Time) *SubtitleUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableUpdateTime(v *time.Time) *SubtitleUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// SetMedia sets the "media" edge to the Media entity.
func (_u *SubtitleUpdateOne) SetMedia(v *Media) *SubtitleUpdateOne {
	return _u.SetMediaID(v.ID)
}

// Mutation returns the SubtitleMutation object of the builder.
func (_u *SubtitleUpdateOne) Mutation() *SubtitleMutation {
	return _u.mutation
}

// ClearMedia clears the "media" edge to the Media entity.
func (_u *SubtitleUpdateOne) ClearMedia() *SubtitleUpdateOne {
	_u.mutation.ClearMedia()
	return _u
}

// Where appends a list predicates to the SubtitleUpdate builder.
func (_u *SubtitleUpdateOne) Where(ps ...predicate.Subtitle) *SubtitleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubtitleUpdateOne) Select(field string, fields ...string) *SubtitleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subtitle entity.
func (_u *SubtitleUpdateOne) Save(ctx context.Context) (*Subtitle, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubtitleUpdateOne) SaveX(ctx context.Context) *Subtitle {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubtitleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubtitleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubtitleUpdateOne) check() error {
	if v, ok := _u.mutation.MediaID(); ok {
		if err := subtitle.MediaIDValidator(v); err != nil {
			return &ValidationError{Name: "media_id", err: fmt.Errorf(`entity: validator failed for field "Subtitle.media_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := subtitle.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`entity: validator failed for field "Subtitle.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := subtitle.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`entity: validator failed for field "Subtitle.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileURL(); ok {
		if err := subtitle.FileURLValidator(v); err != nil {
			return &ValidationError{Name: "file_url", err: fmt.Errorf(`entity: validator failed for field "Subtitle.file_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subtitle.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`entity: validator failed for field "Subtitle.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := subtitle.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`entity: validator failed for field "Subtitle.error_message": %w`, err)}
		}
	}
	if _u.mutation.MediaCleared() && len(_u.mutation.MediaIDs()) > 0 {
		return errors.New(`entity: clearing a required unique edge "Subtitle.media"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SubtitleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SubtitleUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SubtitleUpdateOne) sqlSave(ctx context.Context) (_node *Subtitle, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subtitle.Table, subtitle.Columns, sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entity: missing "Subtitle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subtitle.FieldID)
		for _, f := range fields {
			if !subtitle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entity: invalid field %q for query", f)}
			}
			if f != subtitle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(subtitle.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(subtitle.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(subtitle.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(subtitle.FieldFileURL, field.TypeString, value)
	}
	if _u.mutation.FileURLCleared() {
		_spec.ClearField(subtitle.FieldFileURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subtitle.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(subtitle.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(subtitle.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(subtitle.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(subtitle.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtitle.MediaTable,
			Columns: []string{subtitle.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtitle.MediaTable,
			Columns: []string{subtitle.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Subtitle{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subtitle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
