// Code generated by ent, DO NOT EDIT.

package promotiontask

import (
	"origadmin/application/origstudio/internal/dal/entity/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContainsFold(FieldID, id))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldChannelID, v))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldTemplateID, v))
}

// RenderedSubject applies equality check predicate on the "rendered_subject" field. It's identical to RenderedSubjectEQ.
func RenderedSubject(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldRenderedSubject, v))
}

// RenderedBody applies equality check predicate on the "rendered_body" field. It's identical to RenderedBodyEQ.
func RenderedBody(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldRenderedBody, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldRetryCount, v))
}

// MaxRetries applies equality check predicate on the "max_retries" field. It's identical to MaxRetriesEQ.
func MaxRetries(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldMaxRetries, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldErrorMessage, v))
}

// ScheduledAt applies equality check predicate on the "scheduled_at" field. It's identical to ScheduledAtEQ.
func ScheduledAt(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldScheduledAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldCompletedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldTenantID, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldUpdateTime, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDContains applies the Contains predicate on the "channel_id" field.
func ChannelIDContains(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContains(FieldChannelID, v))
}

// ChannelIDHasPrefix applies the HasPrefix predicate on the "channel_id" field.
func ChannelIDHasPrefix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasPrefix(FieldChannelID, v))
}

// ChannelIDHasSuffix applies the HasSuffix predicate on the "channel_id" field.
func ChannelIDHasSuffix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasSuffix(FieldChannelID, v))
}

// ChannelIDEqualFold applies the EqualFold predicate on the "channel_id" field.
func ChannelIDEqualFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEqualFold(FieldChannelID, v))
}

// ChannelIDContainsFold applies the ContainsFold predicate on the "channel_id" field.
func ChannelIDContainsFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContainsFold(FieldChannelID, v))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldTemplateID, vs...))
}

// TemplateIDGT applies the GT predicate on the "template_id" field.
func TemplateIDGT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldTemplateID, v))
}

// TemplateIDGTE applies the GTE predicate on the "template_id" field.
func TemplateIDGTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldTemplateID, v))
}

// TemplateIDLT applies the LT predicate on the "template_id" field.
func TemplateIDLT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldTemplateID, v))
}

// TemplateIDLTE applies the LTE predicate on the "template_id" field.
func TemplateIDLTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldTemplateID, v))
}

// TemplateIDContains applies the Contains predicate on the "template_id" field.
func TemplateIDContains(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContains(FieldTemplateID, v))
}

// TemplateIDHasPrefix applies the HasPrefix predicate on the "template_id" field.
func TemplateIDHasPrefix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasPrefix(FieldTemplateID, v))
}

// TemplateIDHasSuffix applies the HasSuffix predicate on the "template_id" field.
func TemplateIDHasSuffix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasSuffix(FieldTemplateID, v))
}

// TemplateIDIsNil applies the IsNil predicate on the "template_id" field.
func TemplateIDIsNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIsNull(FieldTemplateID))
}

// TemplateIDNotNil applies the NotNil predicate on the "template_id" field.
func TemplateIDNotNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotNull(FieldTemplateID))
}

// TemplateIDEqualFold applies the EqualFold predicate on the "template_id" field.
func TemplateIDEqualFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEqualFold(FieldTemplateID, v))
}

// TemplateIDContainsFold applies the ContainsFold predicate on the "template_id" field.
func TemplateIDContainsFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContainsFold(FieldTemplateID, v))
}

// TaskTypeEQ applies the EQ predicate on the "task_type" field.
func TaskTypeEQ(v TaskType) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldTaskType, v))
}

// TaskTypeNEQ applies the NEQ predicate on the "task_type" field.
func TaskTypeNEQ(v TaskType) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldTaskType, v))
}

// TaskTypeIn applies the In predicate on the "task_type" field.
func TaskTypeIn(vs ...TaskType) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldTaskType, vs...))
}

// TaskTypeNotIn applies the NotIn predicate on the "task_type" field.
func TaskTypeNotIn(vs ...TaskType) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldTaskType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldStatus, vs...))
}

// MediaIdsIsNil applies the IsNil predicate on the "media_ids" field.
func MediaIdsIsNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIsNull(FieldMediaIds))
}

// MediaIdsNotNil applies the NotNil predicate on the "media_ids" field.
func MediaIdsNotNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotNull(FieldMediaIds))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotNull(FieldPayload))
}

// RenderedSubjectEQ applies the EQ predicate on the "rendered_subject" field.
func RenderedSubjectEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldRenderedSubject, v))
}

// RenderedSubjectNEQ applies the NEQ predicate on the "rendered_subject" field.
func RenderedSubjectNEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldRenderedSubject, v))
}

// RenderedSubjectIn applies the In predicate on the "rendered_subject" field.
func RenderedSubjectIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldRenderedSubject, vs...))
}

// RenderedSubjectNotIn applies the NotIn predicate on the "rendered_subject" field.
func RenderedSubjectNotIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldRenderedSubject, vs...))
}

// RenderedSubjectGT applies the GT predicate on the "rendered_subject" field.
func RenderedSubjectGT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldRenderedSubject, v))
}

// RenderedSubjectGTE applies the GTE predicate on the "rendered_subject" field.
func RenderedSubjectGTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldRenderedSubject, v))
}

// RenderedSubjectLT applies the LT predicate on the "rendered_subject" field.
func RenderedSubjectLT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldRenderedSubject, v))
}

// RenderedSubjectLTE applies the LTE predicate on the "rendered_subject" field.
func RenderedSubjectLTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldRenderedSubject, v))
}

// RenderedSubjectContains applies the Contains predicate on the "rendered_subject" field.
func RenderedSubjectContains(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContains(FieldRenderedSubject, v))
}

// RenderedSubjectHasPrefix applies the HasPrefix predicate on the "rendered_subject" field.
func RenderedSubjectHasPrefix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasPrefix(FieldRenderedSubject, v))
}

// RenderedSubjectHasSuffix applies the HasSuffix predicate on the "rendered_subject" field.
func RenderedSubjectHasSuffix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasSuffix(FieldRenderedSubject, v))
}

// RenderedSubjectIsNil applies the IsNil predicate on the "rendered_subject" field.
func RenderedSubjectIsNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIsNull(FieldRenderedSubject))
}

// RenderedSubjectNotNil applies the NotNil predicate on the "rendered_subject" field.
func RenderedSubjectNotNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotNull(FieldRenderedSubject))
}

// RenderedSubjectEqualFold applies the EqualFold predicate on the "rendered_subject" field.
func RenderedSubjectEqualFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEqualFold(FieldRenderedSubject, v))
}

// RenderedSubjectContainsFold applies the ContainsFold predicate on the "rendered_subject" field.
func RenderedSubjectContainsFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContainsFold(FieldRenderedSubject, v))
}

// RenderedBodyEQ applies the EQ predicate on the "rendered_body" field.
func RenderedBodyEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldRenderedBody, v))
}

// RenderedBodyNEQ applies the NEQ predicate on the "rendered_body" field.
func RenderedBodyNEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldRenderedBody, v))
}

// RenderedBodyIn applies the In predicate on the "rendered_body" field.
func RenderedBodyIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldRenderedBody, vs...))
}

// RenderedBodyNotIn applies the NotIn predicate on the "rendered_body" field.
func RenderedBodyNotIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldRenderedBody, vs...))
}

// RenderedBodyGT applies the GT predicate on the "rendered_body" field.
func RenderedBodyGT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldRenderedBody, v))
}

// RenderedBodyGTE applies the GTE predicate on the "rendered_body" field.
func RenderedBodyGTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldRenderedBody, v))
}

// RenderedBodyLT applies the LT predicate on the "rendered_body" field.
func RenderedBodyLT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldRenderedBody, v))
}

// RenderedBodyLTE applies the LTE predicate on the "rendered_body" field.
func RenderedBodyLTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldRenderedBody, v))
}

// RenderedBodyContains applies the Contains predicate on the "rendered_body" field.
func RenderedBodyContains(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContains(FieldRenderedBody, v))
}

// RenderedBodyHasPrefix applies the HasPrefix predicate on the "rendered_body" field.
func RenderedBodyHasPrefix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasPrefix(FieldRenderedBody, v))
}

// RenderedBodyHasSuffix applies the HasSuffix predicate on the "rendered_body" field.
func RenderedBodyHasSuffix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasSuffix(FieldRenderedBody, v))
}

// RenderedBodyIsNil applies the IsNil predicate on the "rendered_body" field.
func RenderedBodyIsNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIsNull(FieldRenderedBody))
}

// RenderedBodyNotNil applies the NotNil predicate on the "rendered_body" field.
func RenderedBodyNotNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotNull(FieldRenderedBody))
}

// RenderedBodyEqualFold applies the EqualFold predicate on the "rendered_body" field.
func RenderedBodyEqualFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEqualFold(FieldRenderedBody, v))
}

// RenderedBodyContainsFold applies the ContainsFold predicate on the "rendered_body" field.
func RenderedBodyContainsFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContainsFold(FieldRenderedBody, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldRetryCount, v))
}

// MaxRetriesEQ applies the EQ predicate on the "max_retries" field.
func MaxRetriesEQ(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldMaxRetries, v))
}

// MaxRetriesNEQ applies the NEQ predicate on the "max_retries" field.
func MaxRetriesNEQ(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldMaxRetries, v))
}

// MaxRetriesIn applies the In predicate on the "max_retries" field.
func MaxRetriesIn(vs ...int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldMaxRetries, vs...))
}

// MaxRetriesNotIn applies the NotIn predicate on the "max_retries" field.
func MaxRetriesNotIn(vs ...int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldMaxRetries, vs...))
}

// MaxRetriesGT applies the GT predicate on the "max_retries" field.
func MaxRetriesGT(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldMaxRetries, v))
}

// MaxRetriesGTE applies the GTE predicate on the "max_retries" field.
func MaxRetriesGTE(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldMaxRetries, v))
}

// MaxRetriesLT applies the LT predicate on the "max_retries" field.
func MaxRetriesLT(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldMaxRetries, v))
}

// MaxRetriesLTE applies the LTE predicate on the "max_retries" field.
func MaxRetriesLTE(v int) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldMaxRetries, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ScheduledAtEQ applies the EQ predicate on the "scheduled_at" field.
func ScheduledAtEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldScheduledAt, v))
}

// ScheduledAtNEQ applies the NEQ predicate on the "scheduled_at" field.
func ScheduledAtNEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldScheduledAt, v))
}

// ScheduledAtIn applies the In predicate on the "scheduled_at" field.
func ScheduledAtIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldScheduledAt, vs...))
}

// ScheduledAtNotIn applies the NotIn predicate on the "scheduled_at" field.
func ScheduledAtNotIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldScheduledAt, vs...))
}

// ScheduledAtGT applies the GT predicate on the "scheduled_at" field.
func ScheduledAtGT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldScheduledAt, v))
}

// ScheduledAtGTE applies the GTE predicate on the "scheduled_at" field.
func ScheduledAtGTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldScheduledAt, v))
}

// ScheduledAtLT applies the LT predicate on the "scheduled_at" field.
func ScheduledAtLT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldScheduledAt, v))
}

// ScheduledAtLTE applies the LTE predicate on the "scheduled_at" field.
func ScheduledAtLTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldScheduledAt, v))
}

// ScheduledAtIsNil applies the IsNil predicate on the "scheduled_at" field.
func ScheduledAtIsNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIsNull(FieldScheduledAt))
}

// ScheduledAtNotNil applies the NotNil predicate on the "scheduled_at" field.
func ScheduledAtNotNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotNull(FieldScheduledAt))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotNull(FieldCompletedAt))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldContainsFold(FieldTenantID, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.PromotionTask {
	return predicate.PromotionTask(sql.FieldLTE(FieldUpdateTime, v))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.PromotionTask {
	return predicate.PromotionTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.PromotionChannel) predicate.PromotionTask {
	return predicate.PromotionTask(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTemplate applies the HasEdge predicate on the "template" edge.
func HasTemplate() predicate.PromotionTask {
	return predicate.PromotionTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TemplateTable, TemplateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTemplateWith applies the HasEdge predicate on the "template" edge with a given conditions (other predicates).
func HasTemplateWith(preds ...predicate.PromotionTemplate) predicate.PromotionTask {
	return predicate.PromotionTask(func(s *sql.Selector) {
		step := newTemplateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLogs applies the HasEdge predicate on the "logs" edge.
func HasLogs() predicate.PromotionTask {
	return predicate.PromotionTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LogsTable, LogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLogsWith applies the HasEdge predicate on the "logs" edge with a given conditions (other predicates).
func HasLogsWith(preds ...predicate.PromotionLog) predicate.PromotionTask {
	return predicate.PromotionTask(func(s *sql.Selector) {
		step := newLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromotionTask) predicate.PromotionTask {
	return predicate.PromotionTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromotionTask) predicate.PromotionTask {
	return predicate.PromotionTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromotionTask) predicate.PromotionTask {
	return predicate.PromotionTask(sql.NotPredicates(p))
}
