// Code generated by ent, DO NOT EDIT.

package promotionsubscription

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the promotionsubscription type in the database.
	Label = "promotion_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldChannelIds holds the string denoting the channel_ids field in the database.
	FieldChannelIds = "channel_ids"
	// FieldTagIds holds the string denoting the tag_ids field in the database.
	FieldTagIds = "tag_ids"
	// FieldPlatforms holds the string denoting the platforms field in the database.
	FieldPlatforms = "platforms"
	// FieldFrequency holds the string denoting the frequency field in the database.
	FieldFrequency = "frequency"
	// FieldQuietHours holds the string denoting the quiet_hours field in the database.
	FieldQuietHours = "quiet_hours"
	// FieldDailyLimit holds the string denoting the daily_limit field in the database.
	FieldDailyLimit = "daily_limit"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the promotionsubscription in the database.
	Table = "promotion_subscriptions"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "promotion_subscriptions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for promotionsubscription fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldChannelIds,
	FieldTagIds,
	FieldPlatforms,
	FieldFrequency,
	FieldQuietHours,
	FieldDailyLimit,
	FieldIsActive,
	FieldTenantID,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// DefaultDailyLimit holds the default value on creation for the "daily_limit" field.
	DefaultDailyLimit int
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID string
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Frequency defines the type for the "frequency" enum field.
type Frequency string

// FrequencyDaily is the default value of the Frequency enum.
const DefaultFrequency = FrequencyDaily

// Frequency values.
const (
	FrequencyRealtime Frequency = "realtime"
	FrequencyDaily    Frequency = "daily"
	FrequencyWeekly   Frequency = "weekly"
)

func (f Frequency) String() string {
	return string(f)
}

// FrequencyValidator is a validator for the "frequency" field enum values. It is called by the builders before save.
func FrequencyValidator(f Frequency) error {
	switch f {
	case FrequencyRealtime, FrequencyDaily, FrequencyWeekly:
		return nil
	default:
		return fmt.Errorf("promotionsubscription: invalid enum value for frequency field: %q", f)
	}
}

// OrderOption defines the ordering options for the PromotionSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByFrequency orders the results by the frequency field.
func ByFrequency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrequency, opts...).ToFunc()
}

// ByDailyLimit orders the results by the daily_limit field.
func ByDailyLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyLimit, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
