// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"origadmin/application/origcms/internal/data/entity/channel"
	"origadmin/application/origcms/internal/data/entity/media"
	"origadmin/application/origcms/internal/data/entity/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChannelCreate is the builder for creating a Channel entity.
type ChannelCreate struct {
	config
	mutation *ChannelMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ChannelCreate) SetUserID(v string) *ChannelCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ChannelCreate) SetTitle(v string) *ChannelCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ChannelCreate) SetSlug(v string) *ChannelCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ChannelCreate) SetDescription(v string) *ChannelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetShortToken sets the "short_token" field.
func (_c *ChannelCreate) SetShortToken(v string) *ChannelCreate {
	_c.mutation.SetShortToken(v)
	return _c
}

// SetNillableShortToken sets the "short_token" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableShortToken(v *string) *ChannelCreate {
	if v != nil {
		_c.SetShortToken(*v)
	}
	return _c
}

// SetBannerLogo sets the "banner_logo" field.
func (_c *ChannelCreate) SetBannerLogo(v string) *ChannelCreate {
	_c.mutation.SetBannerLogo(v)
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *ChannelCreate) SetIsPublic(v bool) *ChannelCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableIsPublic(v *bool) *ChannelCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetAddDate sets the "add_date" field.
func (_c *ChannelCreate) SetAddDate(v time.Time) *ChannelCreate {
	_c.mutation.SetAddDate(v)
	return _c
}

// SetNillableAddDate sets the "add_date" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableAddDate(v *time.Time) *ChannelCreate {
	if v != nil {
		_c.SetAddDate(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelCreate) SetID(v string) *ChannelCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableID(v *string) *ChannelCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChannelCreate) SetUser(v *User) *ChannelCreate {
	return _c.SetUserID(v.ID)
}

// AddMediumIDs adds the "media" edge to the Media entity by IDs.
func (_c *ChannelCreate) AddMediumIDs(ids ...string) *ChannelCreate {
	_c.mutation.AddMediumIDs(ids...)
	return _c
}

// AddMedia adds the "media" edges to the Media entity.
func (_c *ChannelCreate) AddMedia(v ...*Media) *ChannelCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMediumIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_c *ChannelCreate) Mutation() *ChannelMutation {
	return _c.mutation
}

// Save creates the Channel in the database.
func (_c *ChannelCreate) Save(ctx context.Context) (*Channel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelCreate) SaveX(ctx context.Context) *Channel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelCreate) defaults() {
	if _, ok := _c.mutation.ShortToken(); !ok {
		v := channel.DefaultShortToken()
		_c.mutation.SetShortToken(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := channel.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
	if _, ok := _c.mutation.AddDate(); !ok {
		v := channel.DefaultAddDate()
		_c.mutation.SetAddDate(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := channel.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`entity: missing required field "Channel.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`entity: missing required field "Channel.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := channel.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`entity: validator failed for field "Channel.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`entity: missing required field "Channel.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := channel.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`entity: validator failed for field "Channel.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`entity: missing required field "Channel.description"`)}
	}
	if _, ok := _c.mutation.ShortToken(); !ok {
		return &ValidationError{Name: "short_token", err: errors.New(`entity: missing required field "Channel.short_token"`)}
	}
	if v, ok := _c.mutation.ShortToken(); ok {
		if err := channel.ShortTokenValidator(v); err != nil {
			return &ValidationError{Name: "short_token", err: fmt.Errorf(`entity: validator failed for field "Channel.short_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BannerLogo(); !ok {
		return &ValidationError{Name: "banner_logo", err: errors.New(`entity: missing required field "Channel.banner_logo"`)}
	}
	if v, ok := _c.mutation.BannerLogo(); ok {
		if err := channel.BannerLogoValidator(v); err != nil {
			return &ValidationError{Name: "banner_logo", err: fmt.Errorf(`entity: validator failed for field "Channel.banner_logo": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`entity: missing required field "Channel.is_public"`)}
	}
	if _, ok := _c.mutation.AddDate(); !ok {
		return &ValidationError{Name: "add_date", err: errors.New(`entity: missing required field "Channel.add_date"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := channel.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`entity: validator failed for field "Channel.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`entity: missing required edge "Channel.user"`)}
	}
	return nil
}

func (_c *ChannelCreate) sqlSave(ctx context.Context) (*Channel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Channel.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelCreate) createSpec() (*Channel, *sqlgraph.CreateSpec) {
	var (
		_node = &Channel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channel.Table, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(channel.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(channel.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(channel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ShortToken(); ok {
		_spec.SetField(channel.FieldShortToken, field.TypeString, value)
		_node.ShortToken = value
	}
	if value, ok := _c.mutation.BannerLogo(); ok {
		_spec.SetField(channel.FieldBannerLogo, field.TypeString, value)
		_node.BannerLogo = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(channel.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := _c.mutation.AddDate(); ok {
		_spec.SetField(channel.FieldAddDate, field.TypeTime, value)
		_node.AddDate = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channel.UserTable,
			Columns: []string{channel.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.MediaTable,
			Columns: []string{channel.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChannelCreateBulk is the builder for creating many Channel entities in bulk.
type ChannelCreateBulk struct {
	config
	err      error
	builders []*ChannelCreate
}

// Save creates the Channel entities in the database.
func (_c *ChannelCreateBulk) Save(ctx context.Context) ([]*Channel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Channel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelCreateBulk) SaveX(ctx context.Context) []*Channel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
