// Code generated by ent, DO NOT EDIT.

package entity

import (
	"fmt"
	"origadmin/application/origstudio/internal/data/entity/comment"
	"origadmin/application/origstudio/internal/data/entity/commentlike"
	"origadmin/application/origstudio/internal/data/entity/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CommentLike is the model entity for the CommentLike schema.
type CommentLike struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CommentID holds the value of the "comment_id" field.
	CommentID string `json:"comment_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// LikeType holds the value of the "like_type" field.
	LikeType string `json:"like_type,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CommentLikeQuery when eager-loading is set.
	Edges        CommentLikeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CommentLikeEdges holds the relations/edges for other nodes in the graph.
type CommentLikeEdges struct {
	// Comment holds the value of the comment edge.
	Comment *Comment `json:"comment,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CommentOrErr returns the Comment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommentLikeEdges) CommentOrErr() (*Comment, error) {
	if e.Comment != nil {
		return e.Comment, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: comment.Label}
	}
	return nil, &NotLoadedError{edge: "comment"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommentLikeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CommentLike) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case commentlike.FieldID, commentlike.FieldCommentID, commentlike.FieldUserID, commentlike.FieldLikeType:
			values[i] = new(sql.NullString)
		case commentlike.FieldCreateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CommentLike fields.
func (_m *CommentLike) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case commentlike.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case commentlike.FieldCommentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment_id", values[i])
			} else if value.Valid {
				_m.CommentID = value.String
			}
		case commentlike.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case commentlike.FieldLikeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field like_type", values[i])
			} else if value.Valid {
				_m.LikeType = value.String
			}
		case commentlike.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CommentLike.
// This includes values selected through modifiers, order, etc.
func (_m *CommentLike) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryComment queries the "comment" edge of the CommentLike entity.
func (_m *CommentLike) QueryComment() *CommentQuery {
	return NewCommentLikeClient(_m.config).QueryComment(_m)
}

// QueryUser queries the "user" edge of the CommentLike entity.
func (_m *CommentLike) QueryUser() *UserQuery {
	return NewCommentLikeClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this CommentLike.
// Note that you need to call CommentLike.Unwrap() before calling this method if this CommentLike
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CommentLike) Update() *CommentLikeUpdateOne {
	return NewCommentLikeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CommentLike entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CommentLike) Unwrap() *CommentLike {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("entity: CommentLike is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CommentLike) String() string {
	var builder strings.Builder
	builder.WriteString("CommentLike(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("comment_id=")
	builder.WriteString(_m.CommentID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("like_type=")
	builder.WriteString(_m.LikeType)
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CommentLikes is a parsable slice of CommentLike.
type CommentLikes []*CommentLike
