// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"origadmin/application/origstudio/internal/data/entity/drmpolicy"
	"origadmin/application/origstudio/internal/data/entity/media"
	"origadmin/application/origstudio/internal/data/entity/mediadrmpolicy"
	"origadmin/application/origstudio/internal/data/entity/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaDrmPolicyUpdate is the builder for updating MediaDrmPolicy entities.
type MediaDrmPolicyUpdate struct {
	config
	hooks     []Hook
	mutation  *MediaDrmPolicyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MediaDrmPolicyUpdate builder.
func (_u *MediaDrmPolicyUpdate) Where(ps ...predicate.MediaDrmPolicy) *MediaDrmPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMediaID sets the "media_id" field.
func (_u *MediaDrmPolicyUpdate) SetMediaID(v string) *MediaDrmPolicyUpdate {
	_u.mutation.SetMediaID(v)
	return _u
}

// SetNillableMediaID sets the "media_id" field if the given value is not nil.
func (_u *MediaDrmPolicyUpdate) SetNillableMediaID(v *string) *MediaDrmPolicyUpdate {
	if v != nil {
		_u.SetMediaID(*v)
	}
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *MediaDrmPolicyUpdate) SetPolicyID(v string) *MediaDrmPolicyUpdate {
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *MediaDrmPolicyUpdate) SetNillablePolicyID(v *string) *MediaDrmPolicyUpdate {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *MediaDrmPolicyUpdate) SetCreateTime(v time.Time) *MediaDrmPolicyUpdate {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *MediaDrmPolicyUpdate) SetNillableCreateTime(v *time.Time) *MediaDrmPolicyUpdate {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// SetMedia sets the "media" edge to the Media entity.
func (_u *MediaDrmPolicyUpdate) SetMedia(v *Media) *MediaDrmPolicyUpdate {
	return _u.SetMediaID(v.ID)
}

// SetPolicy sets the "policy" edge to the DrmPolicy entity.
func (_u *MediaDrmPolicyUpdate) SetPolicy(v *DrmPolicy) *MediaDrmPolicyUpdate {
	return _u.SetPolicyID(v.ID)
}

// Mutation returns the MediaDrmPolicyMutation object of the builder.
func (_u *MediaDrmPolicyUpdate) Mutation() *MediaDrmPolicyMutation {
	return _u.mutation
}

// ClearMedia clears the "media" edge to the Media entity.
func (_u *MediaDrmPolicyUpdate) ClearMedia() *MediaDrmPolicyUpdate {
	_u.mutation.ClearMedia()
	return _u
}

// ClearPolicy clears the "policy" edge to the DrmPolicy entity.
func (_u *MediaDrmPolicyUpdate) ClearPolicy() *MediaDrmPolicyUpdate {
	_u.mutation.ClearPolicy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaDrmPolicyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaDrmPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaDrmPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaDrmPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaDrmPolicyUpdate) check() error {
	if v, ok := _u.mutation.MediaID(); ok {
		if err := mediadrmpolicy.MediaIDValidator(v); err != nil {
			return &ValidationError{Name: "media_id", err: fmt.Errorf(`entity: validator failed for field "MediaDrmPolicy.media_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PolicyID(); ok {
		if err := mediadrmpolicy.PolicyIDValidator(v); err != nil {
			return &ValidationError{Name: "policy_id", err: fmt.Errorf(`entity: validator failed for field "MediaDrmPolicy.policy_id": %w`, err)}
		}
	}
	if _u.mutation.MediaCleared() && len(_u.mutation.MediaIDs()) > 0 {
		return errors.New(`entity: clearing a required unique edge "MediaDrmPolicy.media"`)
	}
	if _u.mutation.PolicyCleared() && len(_u.mutation.PolicyIDs()) > 0 {
		return errors.New(`entity: clearing a required unique edge "MediaDrmPolicy.policy"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MediaDrmPolicyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MediaDrmPolicyUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MediaDrmPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediadrmpolicy.Table, mediadrmpolicy.Columns, sqlgraph.NewFieldSpec(mediadrmpolicy.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(mediadrmpolicy.FieldCreateTime, field.TypeTime, value)
	}
	if _u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediadrmpolicy.MediaTable,
			Columns: []string{mediadrmpolicy.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediadrmpolicy.MediaTable,
			Columns: []string{mediadrmpolicy.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PolicyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediadrmpolicy.PolicyTable,
			Columns: []string{mediadrmpolicy.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drmpolicy.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediadrmpolicy.PolicyTable,
			Columns: []string{mediadrmpolicy.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drmpolicy.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediadrmpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaDrmPolicyUpdateOne is the builder for updating a single MediaDrmPolicy entity.
type MediaDrmPolicyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MediaDrmPolicyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetMediaID sets the "media_id" field.
func (_u *MediaDrmPolicyUpdateOne) SetMediaID(v string) *MediaDrmPolicyUpdateOne {
	_u.mutation.SetMediaID(v)
	return _u
}

// SetNillableMediaID sets the "media_id" field if the given value is not nil.
func (_u *MediaDrmPolicyUpdateOne) SetNillableMediaID(v *string) *MediaDrmPolicyUpdateOne {
	if v != nil {
		_u.SetMediaID(*v)
	}
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *MediaDrmPolicyUpdateOne) SetPolicyID(v string) *MediaDrmPolicyUpdateOne {
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *MediaDrmPolicyUpdateOne) SetNillablePolicyID(v *string) *MediaDrmPolicyUpdateOne {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *MediaDrmPolicyUpdateOne) SetCreateTime(v time.Time) *MediaDrmPolicyUpdateOne {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *MediaDrmPolicyUpdateOne) SetNillableCreateTime(v *time.Time) *MediaDrmPolicyUpdateOne {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// SetMedia sets the "media" edge to the Media entity.
func (_u *MediaDrmPolicyUpdateOne) SetMedia(v *Media) *MediaDrmPolicyUpdateOne {
	return _u.SetMediaID(v.ID)
}

// SetPolicy sets the "policy" edge to the DrmPolicy entity.
func (_u *MediaDrmPolicyUpdateOne) SetPolicy(v *DrmPolicy) *MediaDrmPolicyUpdateOne {
	return _u.SetPolicyID(v.ID)
}

// Mutation returns the MediaDrmPolicyMutation object of the builder.
func (_u *MediaDrmPolicyUpdateOne) Mutation() *MediaDrmPolicyMutation {
	return _u.mutation
}

// ClearMedia clears the "media" edge to the Media entity.
func (_u *MediaDrmPolicyUpdateOne) ClearMedia() *MediaDrmPolicyUpdateOne {
	_u.mutation.ClearMedia()
	return _u
}

// ClearPolicy clears the "policy" edge to the DrmPolicy entity.
func (_u *MediaDrmPolicyUpdateOne) ClearPolicy() *MediaDrmPolicyUpdateOne {
	_u.mutation.ClearPolicy()
	return _u
}

// Where appends a list predicates to the MediaDrmPolicyUpdate builder.
func (_u *MediaDrmPolicyUpdateOne) Where(ps ...predicate.MediaDrmPolicy) *MediaDrmPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaDrmPolicyUpdateOne) Select(field string, fields ...string) *MediaDrmPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaDrmPolicy entity.
func (_u *MediaDrmPolicyUpdateOne) Save(ctx context.Context) (*MediaDrmPolicy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaDrmPolicyUpdateOne) SaveX(ctx context.Context) *MediaDrmPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaDrmPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaDrmPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaDrmPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.MediaID(); ok {
		if err := mediadrmpolicy.MediaIDValidator(v); err != nil {
			return &ValidationError{Name: "media_id", err: fmt.Errorf(`entity: validator failed for field "MediaDrmPolicy.media_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PolicyID(); ok {
		if err := mediadrmpolicy.PolicyIDValidator(v); err != nil {
			return &ValidationError{Name: "policy_id", err: fmt.Errorf(`entity: validator failed for field "MediaDrmPolicy.policy_id": %w`, err)}
		}
	}
	if _u.mutation.MediaCleared() && len(_u.mutation.MediaIDs()) > 0 {
		return errors.New(`entity: clearing a required unique edge "MediaDrmPolicy.media"`)
	}
	if _u.mutation.PolicyCleared() && len(_u.mutation.PolicyIDs()) > 0 {
		return errors.New(`entity: clearing a required unique edge "MediaDrmPolicy.policy"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MediaDrmPolicyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MediaDrmPolicyUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MediaDrmPolicyUpdateOne) sqlSave(ctx context.Context) (_node *MediaDrmPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediadrmpolicy.Table, mediadrmpolicy.Columns, sqlgraph.NewFieldSpec(mediadrmpolicy.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entity: missing "MediaDrmPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediadrmpolicy.FieldID)
		for _, f := range fields {
			if !mediadrmpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entity: invalid field %q for query", f)}
			}
			if f != mediadrmpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(mediadrmpolicy.FieldCreateTime, field.TypeTime, value)
	}
	if _u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediadrmpolicy.MediaTable,
			Columns: []string{mediadrmpolicy.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediadrmpolicy.MediaTable,
			Columns: []string{mediadrmpolicy.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PolicyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediadrmpolicy.PolicyTable,
			Columns: []string{mediadrmpolicy.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drmpolicy.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediadrmpolicy.PolicyTable,
			Columns: []string{mediadrmpolicy.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drmpolicy.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MediaDrmPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediadrmpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
