// Code generated by ent, DO NOT EDIT.

package entity

import (
	"fmt"
	"origadmin/application/origcms/internal/data/entity/mediatag"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MediaTag is the model entity for the MediaTag schema.
type MediaTag struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaTagQuery when eager-loading is set.
	Edges          MediaTagEdges `json:"edges"`
	media_tags_rel *int
	selectValues   sql.SelectValues
}

// MediaTagEdges holds the relations/edges for other nodes in the graph.
type MediaTagEdges struct {
	// Media holds the value of the media edge.
	Media []*Media `json:"media,omitempty"`
	// Tag holds the value of the tag edge.
	Tag []*Tag `json:"tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MediaOrErr returns the Media value or an error if the edge
// was not loaded in eager-loading.
func (e MediaTagEdges) MediaOrErr() ([]*Media, error) {
	if e.loadedTypes[0] {
		return e.Media, nil
	}
	return nil, &NotLoadedError{edge: "media"}
}

// TagOrErr returns the Tag value or an error if the edge
// was not loaded in eager-loading.
func (e MediaTagEdges) TagOrErr() ([]*Tag, error) {
	if e.loadedTypes[1] {
		return e.Tag, nil
	}
	return nil, &NotLoadedError{edge: "tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediatag.FieldID:
			values[i] = new(sql.NullInt64)
		case mediatag.ForeignKeys[0]: // media_tags_rel
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaTag fields.
func (_m *MediaTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediatag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mediatag.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field media_tags_rel", value)
			} else if value.Valid {
				_m.media_tags_rel = new(int)
				*_m.media_tags_rel = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaTag.
// This includes values selected through modifiers, order, etc.
func (_m *MediaTag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMedia queries the "media" edge of the MediaTag entity.
func (_m *MediaTag) QueryMedia() *MediaQuery {
	return NewMediaTagClient(_m.config).QueryMedia(_m)
}

// QueryTag queries the "tag" edge of the MediaTag entity.
func (_m *MediaTag) QueryTag() *TagQuery {
	return NewMediaTagClient(_m.config).QueryTag(_m)
}

// Update returns a builder for updating this MediaTag.
// Note that you need to call MediaTag.Unwrap() before calling this method if this MediaTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaTag) Update() *MediaTagUpdateOne {
	return NewMediaTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaTag) Unwrap() *MediaTag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("entity: MediaTag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaTag) String() string {
	var builder strings.Builder
	builder.WriteString("MediaTag(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// MediaTags is a parsable slice of MediaTag.
type MediaTags []*MediaTag
