// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"origadmin/application/origstudio/internal/data/entity/notification"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
}

// SetAction sets the "action" field.
func (_c *NotificationCreate) SetAction(v string) *NotificationCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNotify sets the "notify" field.
func (_c *NotificationCreate) SetNotify(v bool) *NotificationCreate {
	_c.mutation.SetNotify(v)
	return _c
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableNotify(v *bool) *NotificationCreate {
	if v != nil {
		_c.SetNotify(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *NotificationCreate) SetMethod(v string) *NotificationCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableMethod(v *string) *NotificationCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NotificationCreate) SetUserID(v string) *NotificationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetIsRead sets the "is_read" field.
func (_c *NotificationCreate) SetIsRead(v bool) *NotificationCreate {
	_c.mutation.SetIsRead(v)
	return _c
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableIsRead(v *bool) *NotificationCreate {
	if v != nil {
		_c.SetIsRead(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *NotificationCreate) SetCreateTime(v time.Time) *NotificationCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableCreateTime(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *NotificationCreate) SetTitle(v string) *NotificationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *NotificationCreate) SetBody(v string) *NotificationCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *NotificationCreate) SetUpdateTime(v time.Time) *NotificationCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableUpdateTime(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// Mutation returns the NotificationMutation object of the builder.
func (_c *NotificationCreate) Mutation() *NotificationMutation {
	return _c.mutation
}

// Save creates the Notification in the database.
func (_c *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationCreate) defaults() {
	if _, ok := _c.mutation.Notify(); !ok {
		v := notification.DefaultNotify
		_c.mutation.SetNotify(v)
	}
	if _, ok := _c.mutation.Method(); !ok {
		v := notification.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.IsRead(); !ok {
		v := notification.DefaultIsRead
		_c.mutation.SetIsRead(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := notification.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := notification.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationCreate) check() error {
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`entity: missing required field "Notification.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := notification.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`entity: validator failed for field "Notification.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Notify(); !ok {
		return &ValidationError{Name: "notify", err: errors.New(`entity: missing required field "Notification.notify"`)}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`entity: missing required field "Notification.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := notification.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`entity: validator failed for field "Notification.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`entity: missing required field "Notification.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := notification.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`entity: validator failed for field "Notification.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsRead(); !ok {
		return &ValidationError{Name: "is_read", err: errors.New(`entity: missing required field "Notification.is_read"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`entity: missing required field "Notification.create_time"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`entity: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := notification.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`entity: validator failed for field "Notification.body": %w`, err)}
		}
	}
	return nil
}

func (_c *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(notification.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Notify(); ok {
		_spec.SetField(notification.FieldNotify, field.TypeBool, value)
		_node.Notify = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(notification.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
		_node.IsRead = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(notification.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(notification.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	return _node, _spec
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
}

// Save creates the Notification entities in the database.
func (_c *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Notification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
