// Code generated by ent, DO NOT EDIT.

package entity

import (
	"origadmin/application/origcms/internal/data/entity/category"
	"origadmin/application/origcms/internal/data/entity/channel"
	"origadmin/application/origcms/internal/data/entity/comment"
	"origadmin/application/origcms/internal/data/entity/favorite"
	"origadmin/application/origcms/internal/data/entity/like"
	"origadmin/application/origcms/internal/data/entity/media"
	"origadmin/application/origcms/internal/data/entity/mediaplaylist"
	"origadmin/application/origcms/internal/data/entity/notification"
	"origadmin/application/origcms/internal/data/entity/playlist"
	"origadmin/application/origcms/internal/data/entity/schema"
	"origadmin/application/origcms/internal/data/entity/tag"
	"origadmin/application/origcms/internal/data/entity/uploadsession"
	"origadmin/application/origcms/internal/data/entity/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescSlug is the schema descriptor for slug field.
	categoryDescSlug := categoryFields[1].Descriptor()
	// category.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	category.SlugValidator = categoryDescSlug.Validators[0].(func(string) error)
	// categoryDescThumbnail is the schema descriptor for thumbnail field.
	categoryDescThumbnail := categoryFields[3].Descriptor()
	// category.ThumbnailValidator is a validator for the "thumbnail" field. It is called by the builders before save.
	category.ThumbnailValidator = categoryDescThumbnail.Validators[0].(func(string) error)
	// categoryDescListingsThumbnail is the schema descriptor for listings_thumbnail field.
	categoryDescListingsThumbnail := categoryFields[4].Descriptor()
	// category.ListingsThumbnailValidator is a validator for the "listings_thumbnail" field. It is called by the builders before save.
	category.ListingsThumbnailValidator = categoryDescListingsThumbnail.Validators[0].(func(string) error)
	// categoryDescIcon is the schema descriptor for icon field.
	categoryDescIcon := categoryFields[5].Descriptor()
	// category.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	category.IconValidator = categoryDescIcon.Validators[0].(func(string) error)
	// categoryDescColor is the schema descriptor for color field.
	categoryDescColor := categoryFields[6].Descriptor()
	// category.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	category.ColorValidator = categoryDescColor.Validators[0].(func(string) error)
	// categoryDescSequence is the schema descriptor for sequence field.
	categoryDescSequence := categoryFields[8].Descriptor()
	// category.DefaultSequence holds the default value on creation for the sequence field.
	category.DefaultSequence = categoryDescSequence.Default.(int)
	// categoryDescStatus is the schema descriptor for status field.
	categoryDescStatus := categoryFields[9].Descriptor()
	// category.DefaultStatus holds the default value on creation for the status field.
	category.DefaultStatus = categoryDescStatus.Default.(int)
	// categoryDescMediaCount is the schema descriptor for media_count field.
	categoryDescMediaCount := categoryFields[10].Descriptor()
	// category.DefaultMediaCount holds the default value on creation for the media_count field.
	category.DefaultMediaCount = categoryDescMediaCount.Default.(int)
	// categoryDescIsGlobal is the schema descriptor for is_global field.
	categoryDescIsGlobal := categoryFields[11].Descriptor()
	// category.DefaultIsGlobal holds the default value on creation for the is_global field.
	category.DefaultIsGlobal = categoryDescIsGlobal.Default.(bool)
	// categoryDescIsRbacCategory is the schema descriptor for is_rbac_category field.
	categoryDescIsRbacCategory := categoryFields[12].Descriptor()
	// category.DefaultIsRbacCategory holds the default value on creation for the is_rbac_category field.
	category.DefaultIsRbacCategory = categoryDescIsRbacCategory.Default.(bool)
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[15].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryFields[16].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescTitle is the schema descriptor for title field.
	channelDescTitle := channelFields[0].Descriptor()
	// channel.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	channel.TitleValidator = func() func(string) error {
		validators := channelDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// channelDescFriendlyToken is the schema descriptor for friendly_token field.
	channelDescFriendlyToken := channelFields[2].Descriptor()
	// channel.FriendlyTokenValidator is a validator for the "friendly_token" field. It is called by the builders before save.
	channel.FriendlyTokenValidator = channelDescFriendlyToken.Validators[0].(func(string) error)
	// channelDescBannerLogo is the schema descriptor for banner_logo field.
	channelDescBannerLogo := channelFields[3].Descriptor()
	// channel.BannerLogoValidator is a validator for the "banner_logo" field. It is called by the builders before save.
	channel.BannerLogoValidator = channelDescBannerLogo.Validators[0].(func(string) error)
	// channelDescAddDate is the schema descriptor for add_date field.
	channelDescAddDate := channelFields[4].Descriptor()
	// channel.DefaultAddDate holds the default value on creation for the add_date field.
	channel.DefaultAddDate = channelDescAddDate.Default.(func() time.Time)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescAddDate is the schema descriptor for add_date field.
	commentDescAddDate := commentFields[2].Descriptor()
	// comment.DefaultAddDate holds the default value on creation for the add_date field.
	comment.DefaultAddDate = commentDescAddDate.Default.(func() time.Time)
	favoriteFields := schema.Favorite{}.Fields()
	_ = favoriteFields
	// favoriteDescCreatedAt is the schema descriptor for created_at field.
	favoriteDescCreatedAt := favoriteFields[0].Descriptor()
	// favorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	favorite.DefaultCreatedAt = favoriteDescCreatedAt.Default.(func() time.Time)
	likeFields := schema.Like{}.Fields()
	_ = likeFields
	// likeDescCreatedAt is the schema descriptor for created_at field.
	likeDescCreatedAt := likeFields[0].Descriptor()
	// like.DefaultCreatedAt holds the default value on creation for the created_at field.
	like.DefaultCreatedAt = likeDescCreatedAt.Default.(func() time.Time)
	mediaFields := schema.Media{}.Fields()
	_ = mediaFields
	// mediaDescTitle is the schema descriptor for title field.
	mediaDescTitle := mediaFields[0].Descriptor()
	// media.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	media.TitleValidator = mediaDescTitle.Validators[0].(func(string) error)
	// mediaDescFriendlyToken is the schema descriptor for friendly_token field.
	mediaDescFriendlyToken := mediaFields[2].Descriptor()
	// media.FriendlyTokenValidator is a validator for the "friendly_token" field. It is called by the builders before save.
	media.FriendlyTokenValidator = mediaDescFriendlyToken.Validators[0].(func(string) error)
	// mediaDescType is the schema descriptor for type field.
	mediaDescType := mediaFields[3].Descriptor()
	// media.DefaultType holds the default value on creation for the type field.
	media.DefaultType = mediaDescType.Default.(string)
	// media.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	media.TypeValidator = mediaDescType.Validators[0].(func(string) error)
	// mediaDescURL is the schema descriptor for url field.
	mediaDescURL := mediaFields[4].Descriptor()
	// media.URLValidator is a validator for the "url" field. It is called by the builders before save.
	media.URLValidator = mediaDescURL.Validators[0].(func(string) error)
	// mediaDescHlsFile is the schema descriptor for hls_file field.
	mediaDescHlsFile := mediaFields[5].Descriptor()
	// media.HlsFileValidator is a validator for the "hls_file" field. It is called by the builders before save.
	media.HlsFileValidator = mediaDescHlsFile.Validators[0].(func(string) error)
	// mediaDescThumbnail is the schema descriptor for thumbnail field.
	mediaDescThumbnail := mediaFields[6].Descriptor()
	// media.ThumbnailValidator is a validator for the "thumbnail" field. It is called by the builders before save.
	media.ThumbnailValidator = mediaDescThumbnail.Validators[0].(func(string) error)
	// mediaDescPoster is the schema descriptor for poster field.
	mediaDescPoster := mediaFields[7].Descriptor()
	// media.PosterValidator is a validator for the "poster" field. It is called by the builders before save.
	media.PosterValidator = mediaDescPoster.Validators[0].(func(string) error)
	// mediaDescPreviewFilePath is the schema descriptor for preview_file_path field.
	mediaDescPreviewFilePath := mediaFields[8].Descriptor()
	// media.PreviewFilePathValidator is a validator for the "preview_file_path" field. It is called by the builders before save.
	media.PreviewFilePathValidator = mediaDescPreviewFilePath.Validators[0].(func(string) error)
	// mediaDescDuration is the schema descriptor for duration field.
	mediaDescDuration := mediaFields[9].Descriptor()
	// media.DefaultDuration holds the default value on creation for the duration field.
	media.DefaultDuration = mediaDescDuration.Default.(int)
	// mediaDescSize is the schema descriptor for size field.
	mediaDescSize := mediaFields[10].Descriptor()
	// media.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	media.SizeValidator = mediaDescSize.Validators[0].(func(string) error)
	// mediaDescWidth is the schema descriptor for width field.
	mediaDescWidth := mediaFields[11].Descriptor()
	// media.DefaultWidth holds the default value on creation for the width field.
	media.DefaultWidth = mediaDescWidth.Default.(int)
	// mediaDescHeight is the schema descriptor for height field.
	mediaDescHeight := mediaFields[12].Descriptor()
	// media.DefaultHeight holds the default value on creation for the height field.
	media.DefaultHeight = mediaDescHeight.Default.(int)
	// mediaDescMimeType is the schema descriptor for mime_type field.
	mediaDescMimeType := mediaFields[13].Descriptor()
	// media.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	media.MimeTypeValidator = mediaDescMimeType.Validators[0].(func(string) error)
	// mediaDescMd5sum is the schema descriptor for md5sum field.
	mediaDescMd5sum := mediaFields[14].Descriptor()
	// media.Md5sumValidator is a validator for the "md5sum" field. It is called by the builders before save.
	media.Md5sumValidator = mediaDescMd5sum.Validators[0].(func(string) error)
	// mediaDescExtension is the schema descriptor for extension field.
	mediaDescExtension := mediaFields[15].Descriptor()
	// media.ExtensionValidator is a validator for the "extension" field. It is called by the builders before save.
	media.ExtensionValidator = mediaDescExtension.Validators[0].(func(string) error)
	// mediaDescPrivacy is the schema descriptor for privacy field.
	mediaDescPrivacy := mediaFields[16].Descriptor()
	// media.DefaultPrivacy holds the default value on creation for the privacy field.
	media.DefaultPrivacy = mediaDescPrivacy.Default.(int)
	// mediaDescEncodingStatus is the schema descriptor for encoding_status field.
	mediaDescEncodingStatus := mediaFields[17].Descriptor()
	// media.DefaultEncodingStatus holds the default value on creation for the encoding_status field.
	media.DefaultEncodingStatus = mediaDescEncodingStatus.Default.(string)
	// media.EncodingStatusValidator is a validator for the "encoding_status" field. It is called by the builders before save.
	media.EncodingStatusValidator = mediaDescEncodingStatus.Validators[0].(func(string) error)
	// mediaDescState is the schema descriptor for state field.
	mediaDescState := mediaFields[18].Descriptor()
	// media.DefaultState holds the default value on creation for the state field.
	media.DefaultState = mediaDescState.Default.(string)
	// media.StateValidator is a validator for the "state" field. It is called by the builders before save.
	media.StateValidator = mediaDescState.Validators[0].(func(string) error)
	// mediaDescViewCount is the schema descriptor for view_count field.
	mediaDescViewCount := mediaFields[19].Descriptor()
	// media.DefaultViewCount holds the default value on creation for the view_count field.
	media.DefaultViewCount = mediaDescViewCount.Default.(int64)
	// mediaDescLikeCount is the schema descriptor for like_count field.
	mediaDescLikeCount := mediaFields[20].Descriptor()
	// media.DefaultLikeCount holds the default value on creation for the like_count field.
	media.DefaultLikeCount = mediaDescLikeCount.Default.(int64)
	// mediaDescDislikeCount is the schema descriptor for dislike_count field.
	mediaDescDislikeCount := mediaFields[21].Descriptor()
	// media.DefaultDislikeCount holds the default value on creation for the dislike_count field.
	media.DefaultDislikeCount = mediaDescDislikeCount.Default.(int64)
	// mediaDescCommentCount is the schema descriptor for comment_count field.
	mediaDescCommentCount := mediaFields[22].Descriptor()
	// media.DefaultCommentCount holds the default value on creation for the comment_count field.
	media.DefaultCommentCount = mediaDescCommentCount.Default.(int64)
	// mediaDescFavoriteCount is the schema descriptor for favorite_count field.
	mediaDescFavoriteCount := mediaFields[23].Descriptor()
	// media.DefaultFavoriteCount holds the default value on creation for the favorite_count field.
	media.DefaultFavoriteCount = mediaDescFavoriteCount.Default.(int64)
	// mediaDescDownloadCount is the schema descriptor for download_count field.
	mediaDescDownloadCount := mediaFields[24].Descriptor()
	// media.DefaultDownloadCount holds the default value on creation for the download_count field.
	media.DefaultDownloadCount = mediaDescDownloadCount.Default.(int64)
	// mediaDescAllowDownload is the schema descriptor for allow_download field.
	mediaDescAllowDownload := mediaFields[25].Descriptor()
	// media.DefaultAllowDownload holds the default value on creation for the allow_download field.
	media.DefaultAllowDownload = mediaDescAllowDownload.Default.(bool)
	// mediaDescEnableComments is the schema descriptor for enable_comments field.
	mediaDescEnableComments := mediaFields[26].Descriptor()
	// media.DefaultEnableComments holds the default value on creation for the enable_comments field.
	media.DefaultEnableComments = mediaDescEnableComments.Default.(bool)
	// mediaDescFeatured is the schema descriptor for featured field.
	mediaDescFeatured := mediaFields[27].Descriptor()
	// media.DefaultFeatured holds the default value on creation for the featured field.
	media.DefaultFeatured = mediaDescFeatured.Default.(bool)
	// mediaDescIsReviewed is the schema descriptor for is_reviewed field.
	mediaDescIsReviewed := mediaFields[28].Descriptor()
	// media.DefaultIsReviewed holds the default value on creation for the is_reviewed field.
	media.DefaultIsReviewed = mediaDescIsReviewed.Default.(bool)
	// mediaDescReportedTimes is the schema descriptor for reported_times field.
	mediaDescReportedTimes := mediaFields[29].Descriptor()
	// media.DefaultReportedTimes holds the default value on creation for the reported_times field.
	media.DefaultReportedTimes = mediaDescReportedTimes.Default.(int)
	// mediaDescCreatedAt is the schema descriptor for created_at field.
	mediaDescCreatedAt := mediaFields[33].Descriptor()
	// media.DefaultCreatedAt holds the default value on creation for the created_at field.
	media.DefaultCreatedAt = mediaDescCreatedAt.Default.(func() time.Time)
	// mediaDescUpdatedAt is the schema descriptor for updated_at field.
	mediaDescUpdatedAt := mediaFields[34].Descriptor()
	// media.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	media.DefaultUpdatedAt = mediaDescUpdatedAt.Default.(func() time.Time)
	// media.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	media.UpdateDefaultUpdatedAt = mediaDescUpdatedAt.UpdateDefault.(func() time.Time)
	mediaplaylistFields := schema.MediaPlaylist{}.Fields()
	_ = mediaplaylistFields
	// mediaplaylistDescOrdering is the schema descriptor for ordering field.
	mediaplaylistDescOrdering := mediaplaylistFields[0].Descriptor()
	// mediaplaylist.DefaultOrdering holds the default value on creation for the ordering field.
	mediaplaylist.DefaultOrdering = mediaplaylistDescOrdering.Default.(int)
	// mediaplaylistDescActionDate is the schema descriptor for action_date field.
	mediaplaylistDescActionDate := mediaplaylistFields[1].Descriptor()
	// mediaplaylist.DefaultActionDate holds the default value on creation for the action_date field.
	mediaplaylist.DefaultActionDate = mediaplaylistDescActionDate.Default.(func() time.Time)
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescAction is the schema descriptor for action field.
	notificationDescAction := notificationFields[0].Descriptor()
	// notification.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	notification.ActionValidator = notificationDescAction.Validators[0].(func(string) error)
	// notificationDescNotify is the schema descriptor for notify field.
	notificationDescNotify := notificationFields[1].Descriptor()
	// notification.DefaultNotify holds the default value on creation for the notify field.
	notification.DefaultNotify = notificationDescNotify.Default.(bool)
	// notificationDescMethod is the schema descriptor for method field.
	notificationDescMethod := notificationFields[2].Descriptor()
	// notification.DefaultMethod holds the default value on creation for the method field.
	notification.DefaultMethod = notificationDescMethod.Default.(string)
	// notification.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	notification.MethodValidator = notificationDescMethod.Validators[0].(func(string) error)
	playlistFields := schema.Playlist{}.Fields()
	_ = playlistFields
	// playlistDescTitle is the schema descriptor for title field.
	playlistDescTitle := playlistFields[0].Descriptor()
	// playlist.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	playlist.TitleValidator = func() func(string) error {
		validators := playlistDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// playlistDescFriendlyToken is the schema descriptor for friendly_token field.
	playlistDescFriendlyToken := playlistFields[2].Descriptor()
	// playlist.FriendlyTokenValidator is a validator for the "friendly_token" field. It is called by the builders before save.
	playlist.FriendlyTokenValidator = playlistDescFriendlyToken.Validators[0].(func(string) error)
	// playlistDescAddDate is the schema descriptor for add_date field.
	playlistDescAddDate := playlistFields[5].Descriptor()
	// playlist.DefaultAddDate holds the default value on creation for the add_date field.
	playlist.DefaultAddDate = playlistDescAddDate.Default.(func() time.Time)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescTitle is the schema descriptor for title field.
	tagDescTitle := tagFields[0].Descriptor()
	// tag.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	tag.TitleValidator = func() func(string) error {
		validators := tagDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tagDescMediaCount is the schema descriptor for media_count field.
	tagDescMediaCount := tagFields[1].Descriptor()
	// tag.DefaultMediaCount holds the default value on creation for the media_count field.
	tag.DefaultMediaCount = tagDescMediaCount.Default.(int)
	// tagDescListingsThumbnail is the schema descriptor for listings_thumbnail field.
	tagDescListingsThumbnail := tagFields[2].Descriptor()
	// tag.ListingsThumbnailValidator is a validator for the "listings_thumbnail" field. It is called by the builders before save.
	tag.ListingsThumbnailValidator = tagDescListingsThumbnail.Validators[0].(func(string) error)
	uploadsessionFields := schema.UploadSession{}.Fields()
	_ = uploadsessionFields
	// uploadsessionDescUploadID is the schema descriptor for upload_id field.
	uploadsessionDescUploadID := uploadsessionFields[0].Descriptor()
	// uploadsession.UploadIDValidator is a validator for the "upload_id" field. It is called by the builders before save.
	uploadsession.UploadIDValidator = func() func(string) error {
		validators := uploadsessionDescUploadID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(upload_id string) error {
			for _, fn := range fns {
				if err := fn(upload_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadsessionDescFilename is the schema descriptor for filename field.
	uploadsessionDescFilename := uploadsessionFields[1].Descriptor()
	// uploadsession.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	uploadsession.FilenameValidator = func() func(string) error {
		validators := uploadsessionDescFilename.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(filename string) error {
			for _, fn := range fns {
				if err := fn(filename); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadsessionDescFileSize is the schema descriptor for file_size field.
	uploadsessionDescFileSize := uploadsessionFields[2].Descriptor()
	// uploadsession.FileSizeValidator is a validator for the "file_size" field. It is called by the builders before save.
	uploadsession.FileSizeValidator = uploadsessionDescFileSize.Validators[0].(func(int64) error)
	// uploadsessionDescContentType is the schema descriptor for content_type field.
	uploadsessionDescContentType := uploadsessionFields[3].Descriptor()
	// uploadsession.ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	uploadsession.ContentTypeValidator = uploadsessionDescContentType.Validators[0].(func(string) error)
	// uploadsessionDescTotalParts is the schema descriptor for total_parts field.
	uploadsessionDescTotalParts := uploadsessionFields[4].Descriptor()
	// uploadsession.TotalPartsValidator is a validator for the "total_parts" field. It is called by the builders before save.
	uploadsession.TotalPartsValidator = uploadsessionDescTotalParts.Validators[0].(func(int) error)
	// uploadsessionDescChunkSize is the schema descriptor for chunk_size field.
	uploadsessionDescChunkSize := uploadsessionFields[5].Descriptor()
	// uploadsession.DefaultChunkSize holds the default value on creation for the chunk_size field.
	uploadsession.DefaultChunkSize = uploadsessionDescChunkSize.Default.(int)
	// uploadsessionDescUploadedSize is the schema descriptor for uploaded_size field.
	uploadsessionDescUploadedSize := uploadsessionFields[6].Descriptor()
	// uploadsession.DefaultUploadedSize holds the default value on creation for the uploaded_size field.
	uploadsession.DefaultUploadedSize = uploadsessionDescUploadedSize.Default.(int64)
	// uploadsessionDescTitle is the schema descriptor for title field.
	uploadsessionDescTitle := uploadsessionFields[7].Descriptor()
	// uploadsession.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	uploadsession.TitleValidator = uploadsessionDescTitle.Validators[0].(func(string) error)
	// uploadsessionDescStatus is the schema descriptor for status field.
	uploadsessionDescStatus := uploadsessionFields[12].Descriptor()
	// uploadsession.DefaultStatus holds the default value on creation for the status field.
	uploadsession.DefaultStatus = uploadsessionDescStatus.Default.(string)
	// uploadsession.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	uploadsession.StatusValidator = uploadsessionDescStatus.Validators[0].(func(string) error)
	// uploadsessionDescSha256 is the schema descriptor for sha256 field.
	uploadsessionDescSha256 := uploadsessionFields[14].Descriptor()
	// uploadsession.Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	uploadsession.Sha256Validator = uploadsessionDescSha256.Validators[0].(func(string) error)
	// uploadsessionDescStoragePath is the schema descriptor for storage_path field.
	uploadsessionDescStoragePath := uploadsessionFields[15].Descriptor()
	// uploadsession.StoragePathValidator is a validator for the "storage_path" field. It is called by the builders before save.
	uploadsession.StoragePathValidator = uploadsessionDescStoragePath.Validators[0].(func(string) error)
	// uploadsessionDescTempDir is the schema descriptor for temp_dir field.
	uploadsessionDescTempDir := uploadsessionFields[16].Descriptor()
	// uploadsession.TempDirValidator is a validator for the "temp_dir" field. It is called by the builders before save.
	uploadsession.TempDirValidator = uploadsessionDescTempDir.Validators[0].(func(string) error)
	// uploadsessionDescExpiresAt is the schema descriptor for expires_at field.
	uploadsessionDescExpiresAt := uploadsessionFields[17].Descriptor()
	// uploadsession.DefaultExpiresAt holds the default value on creation for the expires_at field.
	uploadsession.DefaultExpiresAt = uploadsessionDescExpiresAt.Default.(func() time.Time)
	// uploadsessionDescCreatedAt is the schema descriptor for created_at field.
	uploadsessionDescCreatedAt := uploadsessionFields[18].Descriptor()
	// uploadsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	uploadsession.DefaultCreatedAt = uploadsessionDescCreatedAt.Default.(func() time.Time)
	// uploadsessionDescUpdatedAt is the schema descriptor for updated_at field.
	uploadsessionDescUpdatedAt := uploadsessionFields[19].Descriptor()
	// uploadsession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	uploadsession.DefaultUpdatedAt = uploadsessionDescUpdatedAt.Default.(func() time.Time)
	// uploadsession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	uploadsession.UpdateDefaultUpdatedAt = uploadsessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[3].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[4].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[5].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[6].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescIsStaff is the schema descriptor for is_staff field.
	userDescIsStaff := userFields[7].Descriptor()
	// user.DefaultIsStaff holds the default value on creation for the is_staff field.
	user.DefaultIsStaff = userDescIsStaff.Default.(bool)
	// userDescIsSuperuser is the schema descriptor for is_superuser field.
	userDescIsSuperuser := userFields[8].Descriptor()
	// user.DefaultIsSuperuser holds the default value on creation for the is_superuser field.
	user.DefaultIsSuperuser = userDescIsSuperuser.Default.(bool)
	// userDescIsFeatured is the schema descriptor for is_featured field.
	userDescIsFeatured := userFields[10].Descriptor()
	// user.DefaultIsFeatured holds the default value on creation for the is_featured field.
	user.DefaultIsFeatured = userDescIsFeatured.Default.(bool)
	// userDescAdvancedUser is the schema descriptor for advanced_user field.
	userDescAdvancedUser := userFields[11].Descriptor()
	// user.DefaultAdvancedUser holds the default value on creation for the advanced_user field.
	user.DefaultAdvancedUser = userDescAdvancedUser.Default.(bool)
	// userDescIsEditor is the schema descriptor for is_editor field.
	userDescIsEditor := userFields[12].Descriptor()
	// user.DefaultIsEditor holds the default value on creation for the is_editor field.
	user.DefaultIsEditor = userDescIsEditor.Default.(bool)
	// userDescIsManager is the schema descriptor for is_manager field.
	userDescIsManager := userFields[13].Descriptor()
	// user.DefaultIsManager holds the default value on creation for the is_manager field.
	user.DefaultIsManager = userDescIsManager.Default.(bool)
	// userDescTitle is the schema descriptor for title field.
	userDescTitle := userFields[14].Descriptor()
	// user.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	user.TitleValidator = userDescTitle.Validators[0].(func(string) error)
	// userDescLogo is the schema descriptor for logo field.
	userDescLogo := userFields[16].Descriptor()
	// user.LogoValidator is a validator for the "logo" field. It is called by the builders before save.
	user.LogoValidator = userDescLogo.Validators[0].(func(string) error)
	// userDescLocation is the schema descriptor for location field.
	userDescLocation := userFields[17].Descriptor()
	// user.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	user.LocationValidator = userDescLocation.Validators[0].(func(string) error)
	// userDescMediaCount is the schema descriptor for media_count field.
	userDescMediaCount := userFields[18].Descriptor()
	// user.DefaultMediaCount holds the default value on creation for the media_count field.
	user.DefaultMediaCount = userDescMediaCount.Default.(int)
	// userDescNotificationOnComments is the schema descriptor for notification_on_comments field.
	userDescNotificationOnComments := userFields[19].Descriptor()
	// user.DefaultNotificationOnComments holds the default value on creation for the notification_on_comments field.
	user.DefaultNotificationOnComments = userDescNotificationOnComments.Default.(bool)
	// userDescAllowContact is the schema descriptor for allow_contact field.
	userDescAllowContact := userFields[20].Descriptor()
	// user.DefaultAllowContact holds the default value on creation for the allow_contact field.
	user.DefaultAllowContact = userDescAllowContact.Default.(bool)
	// userDescDateJoined is the schema descriptor for date_joined field.
	userDescDateJoined := userFields[21].Descriptor()
	// user.DefaultDateJoined holds the default value on creation for the date_joined field.
	user.DefaultDateJoined = userDescDateJoined.Default.(func() time.Time)
	// userDescDateAdded is the schema descriptor for date_added field.
	userDescDateAdded := userFields[22].Descriptor()
	// user.DefaultDateAdded holds the default value on creation for the date_added field.
	user.DefaultDateAdded = userDescDateAdded.Default.(func() time.Time)
}
