// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"origadmin/application/origcms/internal/data/entity/predicate"
	"origadmin/application/origcms/internal/data/entity/uploadsession"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// UploadSessionUpdate is the builder for updating UploadSession entities.
type UploadSessionUpdate struct {
	config
	hooks     []Hook
	mutation  *UploadSessionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UploadSessionUpdate builder.
func (_u *UploadSessionUpdate) Where(ps ...predicate.UploadSession) *UploadSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUploadID sets the "upload_id" field.
func (_u *UploadSessionUpdate) SetUploadID(v string) *UploadSessionUpdate {
	_u.mutation.SetUploadID(v)
	return _u
}

// SetNillableUploadID sets the "upload_id" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableUploadID(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetUploadID(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *UploadSessionUpdate) SetFilename(v string) *UploadSessionUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableFilename(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *UploadSessionUpdate) SetFileSize(v int64) *UploadSessionUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableFileSize(v *int64) *UploadSessionUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *UploadSessionUpdate) AddFileSize(v int64) *UploadSessionUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *UploadSessionUpdate) SetContentType(v string) *UploadSessionUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableContentType(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// ClearContentType clears the value of the "content_type" field.
func (_u *UploadSessionUpdate) ClearContentType() *UploadSessionUpdate {
	_u.mutation.ClearContentType()
	return _u
}

// SetTotalParts sets the "total_parts" field.
func (_u *UploadSessionUpdate) SetTotalParts(v int) *UploadSessionUpdate {
	_u.mutation.ResetTotalParts()
	_u.mutation.SetTotalParts(v)
	return _u
}

// SetNillableTotalParts sets the "total_parts" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableTotalParts(v *int) *UploadSessionUpdate {
	if v != nil {
		_u.SetTotalParts(*v)
	}
	return _u
}

// AddTotalParts adds value to the "total_parts" field.
func (_u *UploadSessionUpdate) AddTotalParts(v int) *UploadSessionUpdate {
	_u.mutation.AddTotalParts(v)
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *UploadSessionUpdate) SetChunkSize(v int) *UploadSessionUpdate {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableChunkSize(v *int) *UploadSessionUpdate {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *UploadSessionUpdate) AddChunkSize(v int) *UploadSessionUpdate {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetUploadedSize sets the "uploaded_size" field.
func (_u *UploadSessionUpdate) SetUploadedSize(v int64) *UploadSessionUpdate {
	_u.mutation.ResetUploadedSize()
	_u.mutation.SetUploadedSize(v)
	return _u
}

// SetNillableUploadedSize sets the "uploaded_size" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableUploadedSize(v *int64) *UploadSessionUpdate {
	if v != nil {
		_u.SetUploadedSize(*v)
	}
	return _u
}

// AddUploadedSize adds value to the "uploaded_size" field.
func (_u *UploadSessionUpdate) AddUploadedSize(v int64) *UploadSessionUpdate {
	_u.mutation.AddUploadedSize(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *UploadSessionUpdate) SetTitle(v string) *UploadSessionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableTitle(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *UploadSessionUpdate) ClearTitle() *UploadSessionUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *UploadSessionUpdate) SetDescription(v string) *UploadSessionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableDescription(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *UploadSessionUpdate) ClearDescription() *UploadSessionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *UploadSessionUpdate) SetCategoryID(v int64) *UploadSessionUpdate {
	_u.mutation.ResetCategoryID()
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableCategoryID(v *int64) *UploadSessionUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// AddCategoryID adds value to the "category_id" field.
func (_u *UploadSessionUpdate) AddCategoryID(v int64) *UploadSessionUpdate {
	_u.mutation.AddCategoryID(v)
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *UploadSessionUpdate) ClearCategoryID() *UploadSessionUpdate {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetTags sets the "tags" field.
func (_u *UploadSessionUpdate) SetTags(v []string) *UploadSessionUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *UploadSessionUpdate) AppendTags(v []string) *UploadSessionUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *UploadSessionUpdate) ClearTags() *UploadSessionUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UploadSessionUpdate) SetUserID(v int64) *UploadSessionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableUserID(v *int64) *UploadSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UploadSessionUpdate) AddUserID(v int64) *UploadSessionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *UploadSessionUpdate) ClearUserID() *UploadSessionUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UploadSessionUpdate) SetStatus(v string) *UploadSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableStatus(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetParts sets the "parts" field.
func (_u *UploadSessionUpdate) SetParts(v map[int]string) *UploadSessionUpdate {
	_u.mutation.SetParts(v)
	return _u
}

// ClearParts clears the value of the "parts" field.
func (_u *UploadSessionUpdate) ClearParts() *UploadSessionUpdate {
	_u.mutation.ClearParts()
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *UploadSessionUpdate) SetSha256(v string) *UploadSessionUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableSha256(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *UploadSessionUpdate) ClearSha256() *UploadSessionUpdate {
	_u.mutation.ClearSha256()
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *UploadSessionUpdate) SetStoragePath(v string) *UploadSessionUpdate {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableStoragePath(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// ClearStoragePath clears the value of the "storage_path" field.
func (_u *UploadSessionUpdate) ClearStoragePath() *UploadSessionUpdate {
	_u.mutation.ClearStoragePath()
	return _u
}

// SetTempDir sets the "temp_dir" field.
func (_u *UploadSessionUpdate) SetTempDir(v string) *UploadSessionUpdate {
	_u.mutation.SetTempDir(v)
	return _u
}

// SetNillableTempDir sets the "temp_dir" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableTempDir(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetTempDir(*v)
	}
	return _u
}

// ClearTempDir clears the value of the "temp_dir" field.
func (_u *UploadSessionUpdate) ClearTempDir() *UploadSessionUpdate {
	_u.mutation.ClearTempDir()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UploadSessionUpdate) SetExpiresAt(v time.Time) *UploadSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableExpiresAt(v *time.Time) *UploadSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UploadSessionUpdate) SetCreatedAt(v time.Time) *UploadSessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableCreatedAt(v *time.Time) *UploadSessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UploadSessionUpdate) SetUpdatedAt(v time.Time) *UploadSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UploadSessionMutation object of the builder.
func (_u *UploadSessionUpdate) Mutation() *UploadSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UploadSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UploadSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UploadSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := uploadsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadSessionUpdate) check() error {
	if v, ok := _u.mutation.UploadID(); ok {
		if err := uploadsession.UploadIDValidator(v); err != nil {
			return &ValidationError{Name: "upload_id", err: fmt.Errorf(`entity: validator failed for field "UploadSession.upload_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filename(); ok {
		if err := uploadsession.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`entity: validator failed for field "UploadSession.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSize(); ok {
		if err := uploadsession.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`entity: validator failed for field "UploadSession.file_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := uploadsession.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`entity: validator failed for field "UploadSession.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalParts(); ok {
		if err := uploadsession.TotalPartsValidator(v); err != nil {
			return &ValidationError{Name: "total_parts", err: fmt.Errorf(`entity: validator failed for field "UploadSession.total_parts": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := uploadsession.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`entity: validator failed for field "UploadSession.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := uploadsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`entity: validator failed for field "UploadSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := uploadsession.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`entity: validator failed for field "UploadSession.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoragePath(); ok {
		if err := uploadsession.StoragePathValidator(v); err != nil {
			return &ValidationError{Name: "storage_path", err: fmt.Errorf(`entity: validator failed for field "UploadSession.storage_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TempDir(); ok {
		if err := uploadsession.TempDirValidator(v); err != nil {
			return &ValidationError{Name: "temp_dir", err: fmt.Errorf(`entity: validator failed for field "UploadSession.temp_dir": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UploadSessionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UploadSessionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UploadSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uploadsession.Table, uploadsession.Columns, sqlgraph.NewFieldSpec(uploadsession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UploadID(); ok {
		_spec.SetField(uploadsession.FieldUploadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(uploadsession.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(uploadsession.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(uploadsession.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(uploadsession.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.ContentTypeCleared() {
		_spec.ClearField(uploadsession.FieldContentType, field.TypeString)
	}
	if value, ok := _u.mutation.TotalParts(); ok {
		_spec.SetField(uploadsession.FieldTotalParts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalParts(); ok {
		_spec.AddField(uploadsession.FieldTotalParts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(uploadsession.FieldChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(uploadsession.FieldChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UploadedSize(); ok {
		_spec.SetField(uploadsession.FieldUploadedSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUploadedSize(); ok {
		_spec.AddField(uploadsession.FieldUploadedSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(uploadsession.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(uploadsession.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(uploadsession.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(uploadsession.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(uploadsession.FieldCategoryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCategoryID(); ok {
		_spec.AddField(uploadsession.FieldCategoryID, field.TypeInt64, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(uploadsession.FieldCategoryID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(uploadsession.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, uploadsession.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(uploadsession.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(uploadsession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(uploadsession.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(uploadsession.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uploadsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parts(); ok {
		_spec.SetField(uploadsession.FieldParts, field.TypeJSON, value)
	}
	if _u.mutation.PartsCleared() {
		_spec.ClearField(uploadsession.FieldParts, field.TypeJSON)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(uploadsession.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(uploadsession.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(uploadsession.FieldStoragePath, field.TypeString, value)
	}
	if _u.mutation.StoragePathCleared() {
		_spec.ClearField(uploadsession.FieldStoragePath, field.TypeString)
	}
	if value, ok := _u.mutation.TempDir(); ok {
		_spec.SetField(uploadsession.FieldTempDir, field.TypeString, value)
	}
	if _u.mutation.TempDirCleared() {
		_spec.ClearField(uploadsession.FieldTempDir, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(uploadsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(uploadsession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadsession.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uploadsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UploadSessionUpdateOne is the builder for updating a single UploadSession entity.
type UploadSessionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UploadSessionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUploadID sets the "upload_id" field.
func (_u *UploadSessionUpdateOne) SetUploadID(v string) *UploadSessionUpdateOne {
	_u.mutation.SetUploadID(v)
	return _u
}

// SetNillableUploadID sets the "upload_id" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableUploadID(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetUploadID(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *UploadSessionUpdateOne) SetFilename(v string) *UploadSessionUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableFilename(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *UploadSessionUpdateOne) SetFileSize(v int64) *UploadSessionUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableFileSize(v *int64) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *UploadSessionUpdateOne) AddFileSize(v int64) *UploadSessionUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *UploadSessionUpdateOne) SetContentType(v string) *UploadSessionUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableContentType(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// ClearContentType clears the value of the "content_type" field.
func (_u *UploadSessionUpdateOne) ClearContentType() *UploadSessionUpdateOne {
	_u.mutation.ClearContentType()
	return _u
}

// SetTotalParts sets the "total_parts" field.
func (_u *UploadSessionUpdateOne) SetTotalParts(v int) *UploadSessionUpdateOne {
	_u.mutation.ResetTotalParts()
	_u.mutation.SetTotalParts(v)
	return _u
}

// SetNillableTotalParts sets the "total_parts" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableTotalParts(v *int) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetTotalParts(*v)
	}
	return _u
}

// AddTotalParts adds value to the "total_parts" field.
func (_u *UploadSessionUpdateOne) AddTotalParts(v int) *UploadSessionUpdateOne {
	_u.mutation.AddTotalParts(v)
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *UploadSessionUpdateOne) SetChunkSize(v int) *UploadSessionUpdateOne {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableChunkSize(v *int) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *UploadSessionUpdateOne) AddChunkSize(v int) *UploadSessionUpdateOne {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetUploadedSize sets the "uploaded_size" field.
func (_u *UploadSessionUpdateOne) SetUploadedSize(v int64) *UploadSessionUpdateOne {
	_u.mutation.ResetUploadedSize()
	_u.mutation.SetUploadedSize(v)
	return _u
}

// SetNillableUploadedSize sets the "uploaded_size" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableUploadedSize(v *int64) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetUploadedSize(*v)
	}
	return _u
}

// AddUploadedSize adds value to the "uploaded_size" field.
func (_u *UploadSessionUpdateOne) AddUploadedSize(v int64) *UploadSessionUpdateOne {
	_u.mutation.AddUploadedSize(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *UploadSessionUpdateOne) SetTitle(v string) *UploadSessionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableTitle(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *UploadSessionUpdateOne) ClearTitle() *UploadSessionUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *UploadSessionUpdateOne) SetDescription(v string) *UploadSessionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableDescription(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *UploadSessionUpdateOne) ClearDescription() *UploadSessionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *UploadSessionUpdateOne) SetCategoryID(v int64) *UploadSessionUpdateOne {
	_u.mutation.ResetCategoryID()
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableCategoryID(v *int64) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// AddCategoryID adds value to the "category_id" field.
func (_u *UploadSessionUpdateOne) AddCategoryID(v int64) *UploadSessionUpdateOne {
	_u.mutation.AddCategoryID(v)
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *UploadSessionUpdateOne) ClearCategoryID() *UploadSessionUpdateOne {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetTags sets the "tags" field.
func (_u *UploadSessionUpdateOne) SetTags(v []string) *UploadSessionUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *UploadSessionUpdateOne) AppendTags(v []string) *UploadSessionUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *UploadSessionUpdateOne) ClearTags() *UploadSessionUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UploadSessionUpdateOne) SetUserID(v int64) *UploadSessionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableUserID(v *int64) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UploadSessionUpdateOne) AddUserID(v int64) *UploadSessionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *UploadSessionUpdateOne) ClearUserID() *UploadSessionUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UploadSessionUpdateOne) SetStatus(v string) *UploadSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableStatus(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetParts sets the "parts" field.
func (_u *UploadSessionUpdateOne) SetParts(v map[int]string) *UploadSessionUpdateOne {
	_u.mutation.SetParts(v)
	return _u
}

// ClearParts clears the value of the "parts" field.
func (_u *UploadSessionUpdateOne) ClearParts() *UploadSessionUpdateOne {
	_u.mutation.ClearParts()
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *UploadSessionUpdateOne) SetSha256(v string) *UploadSessionUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableSha256(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *UploadSessionUpdateOne) ClearSha256() *UploadSessionUpdateOne {
	_u.mutation.ClearSha256()
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *UploadSessionUpdateOne) SetStoragePath(v string) *UploadSessionUpdateOne {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableStoragePath(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// ClearStoragePath clears the value of the "storage_path" field.
func (_u *UploadSessionUpdateOne) ClearStoragePath() *UploadSessionUpdateOne {
	_u.mutation.ClearStoragePath()
	return _u
}

// SetTempDir sets the "temp_dir" field.
func (_u *UploadSessionUpdateOne) SetTempDir(v string) *UploadSessionUpdateOne {
	_u.mutation.SetTempDir(v)
	return _u
}

// SetNillableTempDir sets the "temp_dir" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableTempDir(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetTempDir(*v)
	}
	return _u
}

// ClearTempDir clears the value of the "temp_dir" field.
func (_u *UploadSessionUpdateOne) ClearTempDir() *UploadSessionUpdateOne {
	_u.mutation.ClearTempDir()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UploadSessionUpdateOne) SetExpiresAt(v time.Time) *UploadSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UploadSessionUpdateOne) SetCreatedAt(v time.Time) *UploadSessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableCreatedAt(v *time.Time) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UploadSessionUpdateOne) SetUpdatedAt(v time.Time) *UploadSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UploadSessionMutation object of the builder.
func (_u *UploadSessionUpdateOne) Mutation() *UploadSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the UploadSessionUpdate builder.
func (_u *UploadSessionUpdateOne) Where(ps ...predicate.UploadSession) *UploadSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UploadSessionUpdateOne) Select(field string, fields ...string) *UploadSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UploadSession entity.
func (_u *UploadSessionUpdateOne) Save(ctx context.Context) (*UploadSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadSessionUpdateOne) SaveX(ctx context.Context) *UploadSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UploadSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UploadSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := uploadsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadSessionUpdateOne) check() error {
	if v, ok := _u.mutation.UploadID(); ok {
		if err := uploadsession.UploadIDValidator(v); err != nil {
			return &ValidationError{Name: "upload_id", err: fmt.Errorf(`entity: validator failed for field "UploadSession.upload_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filename(); ok {
		if err := uploadsession.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`entity: validator failed for field "UploadSession.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSize(); ok {
		if err := uploadsession.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`entity: validator failed for field "UploadSession.file_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := uploadsession.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`entity: validator failed for field "UploadSession.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalParts(); ok {
		if err := uploadsession.TotalPartsValidator(v); err != nil {
			return &ValidationError{Name: "total_parts", err: fmt.Errorf(`entity: validator failed for field "UploadSession.total_parts": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := uploadsession.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`entity: validator failed for field "UploadSession.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := uploadsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`entity: validator failed for field "UploadSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := uploadsession.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`entity: validator failed for field "UploadSession.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoragePath(); ok {
		if err := uploadsession.StoragePathValidator(v); err != nil {
			return &ValidationError{Name: "storage_path", err: fmt.Errorf(`entity: validator failed for field "UploadSession.storage_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TempDir(); ok {
		if err := uploadsession.TempDirValidator(v); err != nil {
			return &ValidationError{Name: "temp_dir", err: fmt.Errorf(`entity: validator failed for field "UploadSession.temp_dir": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UploadSessionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UploadSessionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UploadSessionUpdateOne) sqlSave(ctx context.Context) (_node *UploadSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uploadsession.Table, uploadsession.Columns, sqlgraph.NewFieldSpec(uploadsession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entity: missing "UploadSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uploadsession.FieldID)
		for _, f := range fields {
			if !uploadsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entity: invalid field %q for query", f)}
			}
			if f != uploadsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UploadID(); ok {
		_spec.SetField(uploadsession.FieldUploadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(uploadsession.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(uploadsession.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(uploadsession.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(uploadsession.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.ContentTypeCleared() {
		_spec.ClearField(uploadsession.FieldContentType, field.TypeString)
	}
	if value, ok := _u.mutation.TotalParts(); ok {
		_spec.SetField(uploadsession.FieldTotalParts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalParts(); ok {
		_spec.AddField(uploadsession.FieldTotalParts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(uploadsession.FieldChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(uploadsession.FieldChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UploadedSize(); ok {
		_spec.SetField(uploadsession.FieldUploadedSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUploadedSize(); ok {
		_spec.AddField(uploadsession.FieldUploadedSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(uploadsession.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(uploadsession.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(uploadsession.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(uploadsession.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(uploadsession.FieldCategoryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCategoryID(); ok {
		_spec.AddField(uploadsession.FieldCategoryID, field.TypeInt64, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(uploadsession.FieldCategoryID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(uploadsession.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, uploadsession.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(uploadsession.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(uploadsession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(uploadsession.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(uploadsession.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uploadsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parts(); ok {
		_spec.SetField(uploadsession.FieldParts, field.TypeJSON, value)
	}
	if _u.mutation.PartsCleared() {
		_spec.ClearField(uploadsession.FieldParts, field.TypeJSON)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(uploadsession.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(uploadsession.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(uploadsession.FieldStoragePath, field.TypeString, value)
	}
	if _u.mutation.StoragePathCleared() {
		_spec.ClearField(uploadsession.FieldStoragePath, field.TypeString)
	}
	if value, ok := _u.mutation.TempDir(); ok {
		_spec.SetField(uploadsession.FieldTempDir, field.TypeString, value)
	}
	if _u.mutation.TempDirCleared() {
		_spec.ClearField(uploadsession.FieldTempDir, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(uploadsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(uploadsession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadsession.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UploadSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uploadsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
