// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"origadmin/application/origcms/internal/data/entity/category"
	"origadmin/application/origcms/internal/data/entity/channel"
	"origadmin/application/origcms/internal/data/entity/comment"
	"origadmin/application/origcms/internal/data/entity/favorite"
	"origadmin/application/origcms/internal/data/entity/like"
	"origadmin/application/origcms/internal/data/entity/media"
	"origadmin/application/origcms/internal/data/entity/notification"
	"origadmin/application/origcms/internal/data/entity/playlist"
	"origadmin/application/origcms/internal/data/entity/tag"
	"origadmin/application/origcms/internal/data/entity/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *UserCreate) SetUsername(v string) *UserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *UserCreate) SetPassword(v string) *UserCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFirstName sets the "first_name" field.
func (_c *UserCreate) SetFirstName(v string) *UserCreate {
	_c.mutation.SetFirstName(v)
	return _c
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_c *UserCreate) SetNillableFirstName(v *string) *UserCreate {
	if v != nil {
		_c.SetFirstName(*v)
	}
	return _c
}

// SetLastName sets the "last_name" field.
func (_c *UserCreate) SetLastName(v string) *UserCreate {
	_c.mutation.SetLastName(v)
	return _c
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_c *UserCreate) SetNillableLastName(v *string) *UserCreate {
	if v != nil {
		_c.SetLastName(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *UserCreate) SetIsActive(v bool) *UserCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsActive(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetIsStaff sets the "is_staff" field.
func (_c *UserCreate) SetIsStaff(v bool) *UserCreate {
	_c.mutation.SetIsStaff(v)
	return _c
}

// SetNillableIsStaff sets the "is_staff" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsStaff(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsStaff(*v)
	}
	return _c
}

// SetIsSuperuser sets the "is_superuser" field.
func (_c *UserCreate) SetIsSuperuser(v bool) *UserCreate {
	_c.mutation.SetIsSuperuser(v)
	return _c
}

// SetNillableIsSuperuser sets the "is_superuser" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsSuperuser(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsSuperuser(*v)
	}
	return _c
}

// SetIsApproved sets the "is_approved" field.
func (_c *UserCreate) SetIsApproved(v bool) *UserCreate {
	_c.mutation.SetIsApproved(v)
	return _c
}

// SetNillableIsApproved sets the "is_approved" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsApproved(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsApproved(*v)
	}
	return _c
}

// SetIsFeatured sets the "is_featured" field.
func (_c *UserCreate) SetIsFeatured(v bool) *UserCreate {
	_c.mutation.SetIsFeatured(v)
	return _c
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsFeatured(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsFeatured(*v)
	}
	return _c
}

// SetAdvancedUser sets the "advanced_user" field.
func (_c *UserCreate) SetAdvancedUser(v bool) *UserCreate {
	_c.mutation.SetAdvancedUser(v)
	return _c
}

// SetNillableAdvancedUser sets the "advanced_user" field if the given value is not nil.
func (_c *UserCreate) SetNillableAdvancedUser(v *bool) *UserCreate {
	if v != nil {
		_c.SetAdvancedUser(*v)
	}
	return _c
}

// SetIsEditor sets the "is_editor" field.
func (_c *UserCreate) SetIsEditor(v bool) *UserCreate {
	_c.mutation.SetIsEditor(v)
	return _c
}

// SetNillableIsEditor sets the "is_editor" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsEditor(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsEditor(*v)
	}
	return _c
}

// SetIsManager sets the "is_manager" field.
func (_c *UserCreate) SetIsManager(v bool) *UserCreate {
	_c.mutation.SetIsManager(v)
	return _c
}

// SetNillableIsManager sets the "is_manager" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsManager(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsManager(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *UserCreate) SetTitle(v string) *UserCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *UserCreate) SetNillableTitle(v *string) *UserCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *UserCreate) SetDescription(v string) *UserCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *UserCreate) SetNillableDescription(v *string) *UserCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLogo sets the "logo" field.
func (_c *UserCreate) SetLogo(v string) *UserCreate {
	_c.mutation.SetLogo(v)
	return _c
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (_c *UserCreate) SetNillableLogo(v *string) *UserCreate {
	if v != nil {
		_c.SetLogo(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *UserCreate) SetLocation(v string) *UserCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *UserCreate) SetNillableLocation(v *string) *UserCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetMediaCount sets the "media_count" field.
func (_c *UserCreate) SetMediaCount(v int) *UserCreate {
	_c.mutation.SetMediaCount(v)
	return _c
}

// SetNillableMediaCount sets the "media_count" field if the given value is not nil.
func (_c *UserCreate) SetNillableMediaCount(v *int) *UserCreate {
	if v != nil {
		_c.SetMediaCount(*v)
	}
	return _c
}

// SetNotificationOnComments sets the "notification_on_comments" field.
func (_c *UserCreate) SetNotificationOnComments(v bool) *UserCreate {
	_c.mutation.SetNotificationOnComments(v)
	return _c
}

// SetNillableNotificationOnComments sets the "notification_on_comments" field if the given value is not nil.
func (_c *UserCreate) SetNillableNotificationOnComments(v *bool) *UserCreate {
	if v != nil {
		_c.SetNotificationOnComments(*v)
	}
	return _c
}

// SetAllowContact sets the "allow_contact" field.
func (_c *UserCreate) SetAllowContact(v bool) *UserCreate {
	_c.mutation.SetAllowContact(v)
	return _c
}

// SetNillableAllowContact sets the "allow_contact" field if the given value is not nil.
func (_c *UserCreate) SetNillableAllowContact(v *bool) *UserCreate {
	if v != nil {
		_c.SetAllowContact(*v)
	}
	return _c
}

// SetDateJoined sets the "date_joined" field.
func (_c *UserCreate) SetDateJoined(v time.Time) *UserCreate {
	_c.mutation.SetDateJoined(v)
	return _c
}

// SetNillableDateJoined sets the "date_joined" field if the given value is not nil.
func (_c *UserCreate) SetNillableDateJoined(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetDateJoined(*v)
	}
	return _c
}

// SetDateAdded sets the "date_added" field.
func (_c *UserCreate) SetDateAdded(v time.Time) *UserCreate {
	_c.mutation.SetDateAdded(v)
	return _c
}

// SetNillableDateAdded sets the "date_added" field if the given value is not nil.
func (_c *UserCreate) SetNillableDateAdded(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetDateAdded(*v)
	}
	return _c
}

// SetLastLogin sets the "last_login" field.
func (_c *UserCreate) SetLastLogin(v time.Time) *UserCreate {
	_c.mutation.SetLastLogin(v)
	return _c
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_c *UserCreate) SetNillableLastLogin(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetLastLogin(*v)
	}
	return _c
}

// AddMediumIDs adds the "media" edge to the Media entity by IDs.
func (_c *UserCreate) AddMediumIDs(ids ...int) *UserCreate {
	_c.mutation.AddMediumIDs(ids...)
	return _c
}

// AddMedia adds the "media" edges to the Media entity.
func (_c *UserCreate) AddMedia(v ...*Media) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMediumIDs(ids...)
}

// AddChannelIDs adds the "channels" edge to the Channel entity by IDs.
func (_c *UserCreate) AddChannelIDs(ids ...int) *UserCreate {
	_c.mutation.AddChannelIDs(ids...)
	return _c
}

// AddChannels adds the "channels" edges to the Channel entity.
func (_c *UserCreate) AddChannels(v ...*Channel) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChannelIDs(ids...)
}

// AddPlaylistIDs adds the "playlists" edge to the Playlist entity by IDs.
func (_c *UserCreate) AddPlaylistIDs(ids ...int) *UserCreate {
	_c.mutation.AddPlaylistIDs(ids...)
	return _c
}

// AddPlaylists adds the "playlists" edges to the Playlist entity.
func (_c *UserCreate) AddPlaylists(v ...*Playlist) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPlaylistIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_c *UserCreate) AddCommentIDs(ids ...int) *UserCreate {
	_c.mutation.AddCommentIDs(ids...)
	return _c
}

// AddComments adds the "comments" edges to the Comment entity.
func (_c *UserCreate) AddComments(v ...*Comment) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommentIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_c *UserCreate) AddNotificationIDs(ids ...int) *UserCreate {
	_c.mutation.AddNotificationIDs(ids...)
	return _c
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_c *UserCreate) AddNotifications(v ...*Notification) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotificationIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_c *UserCreate) AddCategoryIDs(ids ...int) *UserCreate {
	_c.mutation.AddCategoryIDs(ids...)
	return _c
}

// AddCategories adds the "categories" edges to the Category entity.
func (_c *UserCreate) AddCategories(v ...*Category) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCategoryIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_c *UserCreate) AddTagIDs(ids ...int) *UserCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the Tag entity.
func (_c *UserCreate) AddTags(v ...*Tag) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// AddFavoriteIDs adds the "favorites" edge to the Favorite entity by IDs.
func (_c *UserCreate) AddFavoriteIDs(ids ...int) *UserCreate {
	_c.mutation.AddFavoriteIDs(ids...)
	return _c
}

// AddFavorites adds the "favorites" edges to the Favorite entity.
func (_c *UserCreate) AddFavorites(v ...*Favorite) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFavoriteIDs(ids...)
}

// AddLikeIDs adds the "likes" edge to the Like entity by IDs.
func (_c *UserCreate) AddLikeIDs(ids ...int) *UserCreate {
	_c.mutation.AddLikeIDs(ids...)
	return _c
}

// AddLikes adds the "likes" edges to the Like entity.
func (_c *UserCreate) AddLikes(v ...*Like) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLikeIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := user.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.IsStaff(); !ok {
		v := user.DefaultIsStaff
		_c.mutation.SetIsStaff(v)
	}
	if _, ok := _c.mutation.IsSuperuser(); !ok {
		v := user.DefaultIsSuperuser
		_c.mutation.SetIsSuperuser(v)
	}
	if _, ok := _c.mutation.IsFeatured(); !ok {
		v := user.DefaultIsFeatured
		_c.mutation.SetIsFeatured(v)
	}
	if _, ok := _c.mutation.AdvancedUser(); !ok {
		v := user.DefaultAdvancedUser
		_c.mutation.SetAdvancedUser(v)
	}
	if _, ok := _c.mutation.IsEditor(); !ok {
		v := user.DefaultIsEditor
		_c.mutation.SetIsEditor(v)
	}
	if _, ok := _c.mutation.IsManager(); !ok {
		v := user.DefaultIsManager
		_c.mutation.SetIsManager(v)
	}
	if _, ok := _c.mutation.MediaCount(); !ok {
		v := user.DefaultMediaCount
		_c.mutation.SetMediaCount(v)
	}
	if _, ok := _c.mutation.NotificationOnComments(); !ok {
		v := user.DefaultNotificationOnComments
		_c.mutation.SetNotificationOnComments(v)
	}
	if _, ok := _c.mutation.AllowContact(); !ok {
		v := user.DefaultAllowContact
		_c.mutation.SetAllowContact(v)
	}
	if _, ok := _c.mutation.DateJoined(); !ok {
		v := user.DefaultDateJoined()
		_c.mutation.SetDateJoined(v)
	}
	if _, ok := _c.mutation.DateAdded(); !ok {
		v := user.DefaultDateAdded()
		_c.mutation.SetDateAdded(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`entity: missing required field "User.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`entity: validator failed for field "User.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`entity: missing required field "User.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`entity: validator failed for field "User.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`entity: missing required field "User.password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`entity: validator failed for field "User.password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`entity: missing required field "User.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entity: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FirstName(); ok {
		if err := user.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`entity: validator failed for field "User.first_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastName(); ok {
		if err := user.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`entity: validator failed for field "User.last_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`entity: missing required field "User.is_active"`)}
	}
	if _, ok := _c.mutation.IsStaff(); !ok {
		return &ValidationError{Name: "is_staff", err: errors.New(`entity: missing required field "User.is_staff"`)}
	}
	if _, ok := _c.mutation.IsSuperuser(); !ok {
		return &ValidationError{Name: "is_superuser", err: errors.New(`entity: missing required field "User.is_superuser"`)}
	}
	if _, ok := _c.mutation.IsFeatured(); !ok {
		return &ValidationError{Name: "is_featured", err: errors.New(`entity: missing required field "User.is_featured"`)}
	}
	if _, ok := _c.mutation.AdvancedUser(); !ok {
		return &ValidationError{Name: "advanced_user", err: errors.New(`entity: missing required field "User.advanced_user"`)}
	}
	if _, ok := _c.mutation.IsEditor(); !ok {
		return &ValidationError{Name: "is_editor", err: errors.New(`entity: missing required field "User.is_editor"`)}
	}
	if _, ok := _c.mutation.IsManager(); !ok {
		return &ValidationError{Name: "is_manager", err: errors.New(`entity: missing required field "User.is_manager"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := user.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`entity: validator failed for field "User.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Logo(); ok {
		if err := user.LogoValidator(v); err != nil {
			return &ValidationError{Name: "logo", err: fmt.Errorf(`entity: validator failed for field "User.logo": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Location(); ok {
		if err := user.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`entity: validator failed for field "User.location": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MediaCount(); !ok {
		return &ValidationError{Name: "media_count", err: errors.New(`entity: missing required field "User.media_count"`)}
	}
	if _, ok := _c.mutation.NotificationOnComments(); !ok {
		return &ValidationError{Name: "notification_on_comments", err: errors.New(`entity: missing required field "User.notification_on_comments"`)}
	}
	if _, ok := _c.mutation.AllowContact(); !ok {
		return &ValidationError{Name: "allow_contact", err: errors.New(`entity: missing required field "User.allow_contact"`)}
	}
	if _, ok := _c.mutation.DateJoined(); !ok {
		return &ValidationError{Name: "date_joined", err: errors.New(`entity: missing required field "User.date_joined"`)}
	}
	if _, ok := _c.mutation.DateAdded(); !ok {
		return &ValidationError{Name: "date_added", err: errors.New(`entity: missing required field "User.date_added"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.FirstName(); ok {
		_spec.SetField(user.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := _c.mutation.LastName(); ok {
		_spec.SetField(user.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.IsStaff(); ok {
		_spec.SetField(user.FieldIsStaff, field.TypeBool, value)
		_node.IsStaff = value
	}
	if value, ok := _c.mutation.IsSuperuser(); ok {
		_spec.SetField(user.FieldIsSuperuser, field.TypeBool, value)
		_node.IsSuperuser = value
	}
	if value, ok := _c.mutation.IsApproved(); ok {
		_spec.SetField(user.FieldIsApproved, field.TypeBool, value)
		_node.IsApproved = value
	}
	if value, ok := _c.mutation.IsFeatured(); ok {
		_spec.SetField(user.FieldIsFeatured, field.TypeBool, value)
		_node.IsFeatured = value
	}
	if value, ok := _c.mutation.AdvancedUser(); ok {
		_spec.SetField(user.FieldAdvancedUser, field.TypeBool, value)
		_node.AdvancedUser = value
	}
	if value, ok := _c.mutation.IsEditor(); ok {
		_spec.SetField(user.FieldIsEditor, field.TypeBool, value)
		_node.IsEditor = value
	}
	if value, ok := _c.mutation.IsManager(); ok {
		_spec.SetField(user.FieldIsManager, field.TypeBool, value)
		_node.IsManager = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(user.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(user.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Logo(); ok {
		_spec.SetField(user.FieldLogo, field.TypeString, value)
		_node.Logo = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(user.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.MediaCount(); ok {
		_spec.SetField(user.FieldMediaCount, field.TypeInt, value)
		_node.MediaCount = value
	}
	if value, ok := _c.mutation.NotificationOnComments(); ok {
		_spec.SetField(user.FieldNotificationOnComments, field.TypeBool, value)
		_node.NotificationOnComments = value
	}
	if value, ok := _c.mutation.AllowContact(); ok {
		_spec.SetField(user.FieldAllowContact, field.TypeBool, value)
		_node.AllowContact = value
	}
	if value, ok := _c.mutation.DateJoined(); ok {
		_spec.SetField(user.FieldDateJoined, field.TypeTime, value)
		_node.DateJoined = value
	}
	if value, ok := _c.mutation.DateAdded(); ok {
		_spec.SetField(user.FieldDateAdded, field.TypeTime, value)
		_node.DateAdded = value
	}
	if value, ok := _c.mutation.LastLogin(); ok {
		_spec.SetField(user.FieldLastLogin, field.TypeTime, value)
		_node.LastLogin = value
	}
	if nodes := _c.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.MediaTable,
			Columns: user.MediaPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelsTable,
			Columns: []string{user.ChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlaylistsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.PlaylistsTable,
			Columns: user.PlaylistsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.CommentsTable,
			Columns: user.CommentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: user.NotificationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CategoriesTable,
			Columns: []string{user.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.TagsTable,
			Columns: user.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FavoritesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FavoritesTable,
			Columns: []string{user.FavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(favorite.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LikesTable,
			Columns: []string{user.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(like.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
