// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"
	"origadmin/application/origstudio/internal/data/entity/predicate"
	"origadmin/application/origstudio/internal/data/entity/wallet"
	"origadmin/application/origstudio/internal/data/entity/wallettransaction"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WalletTransactionUpdate is the builder for updating WalletTransaction entities.
type WalletTransactionUpdate struct {
	config
	hooks     []Hook
	mutation  *WalletTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the WalletTransactionUpdate builder.
func (_u *WalletTransactionUpdate) Where(ps ...predicate.WalletTransaction) *WalletTransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *WalletTransactionUpdate) SetType(v wallettransaction.Type) *WalletTransactionUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *WalletTransactionUpdate) SetNillableType(v *wallettransaction.Type) *WalletTransactionUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *WalletTransactionUpdate) SetAmount(v float64) *WalletTransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *WalletTransactionUpdate) SetNillableAmount(v *float64) *WalletTransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *WalletTransactionUpdate) AddAmount(v float64) *WalletTransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *WalletTransactionUpdate) SetBalanceBefore(v float64) *WalletTransactionUpdate {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *WalletTransactionUpdate) SetNillableBalanceBefore(v *float64) *WalletTransactionUpdate {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *WalletTransactionUpdate) AddBalanceBefore(v float64) *WalletTransactionUpdate {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *WalletTransactionUpdate) SetBalanceAfter(v float64) *WalletTransactionUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *WalletTransactionUpdate) SetNillableBalanceAfter(v *float64) *WalletTransactionUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *WalletTransactionUpdate) AddBalanceAfter(v float64) *WalletTransactionUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetReference sets the "reference" field.
func (_u *WalletTransactionUpdate) SetReference(v string) *WalletTransactionUpdate {
	_u.mutation.SetReference(v)
	return _u
}

// SetNillableReference sets the "reference" field if the given value is not nil.
func (_u *WalletTransactionUpdate) SetNillableReference(v *string) *WalletTransactionUpdate {
	if v != nil {
		_u.SetReference(*v)
	}
	return _u
}

// ClearReference clears the value of the "reference" field.
func (_u *WalletTransactionUpdate) ClearReference() *WalletTransactionUpdate {
	_u.mutation.ClearReference()
	return _u
}

// SetDescription sets the "description" field.
func (_u *WalletTransactionUpdate) SetDescription(v string) *WalletTransactionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WalletTransactionUpdate) SetNillableDescription(v *string) *WalletTransactionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *WalletTransactionUpdate) ClearDescription() *WalletTransactionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetWalletID sets the "wallet_id" field.
func (_u *WalletTransactionUpdate) SetWalletID(v string) *WalletTransactionUpdate {
	_u.mutation.SetWalletID(v)
	return _u
}

// SetNillableWalletID sets the "wallet_id" field if the given value is not nil.
func (_u *WalletTransactionUpdate) SetNillableWalletID(v *string) *WalletTransactionUpdate {
	if v != nil {
		_u.SetWalletID(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *WalletTransactionUpdate) SetCreateTime(v time.Time) *WalletTransactionUpdate {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *WalletTransactionUpdate) SetNillableCreateTime(v *time.Time) *WalletTransactionUpdate {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (_u *WalletTransactionUpdate) SetWallet(v *Wallet) *WalletTransactionUpdate {
	return _u.SetWalletID(v.ID)
}

// Mutation returns the WalletTransactionMutation object of the builder.
func (_u *WalletTransactionUpdate) Mutation() *WalletTransactionMutation {
	return _u.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (_u *WalletTransactionUpdate) ClearWallet() *WalletTransactionUpdate {
	_u.mutation.ClearWallet()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WalletTransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WalletTransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletTransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletTransactionUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := wallettransaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`entity: validator failed for field "WalletTransaction.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reference(); ok {
		if err := wallettransaction.ReferenceValidator(v); err != nil {
			return &ValidationError{Name: "reference", err: fmt.Errorf(`entity: validator failed for field "WalletTransaction.reference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := wallettransaction.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`entity: validator failed for field "WalletTransaction.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletID(); ok {
		if err := wallettransaction.WalletIDValidator(v); err != nil {
			return &ValidationError{Name: "wallet_id", err: fmt.Errorf(`entity: validator failed for field "WalletTransaction.wallet_id": %w`, err)}
		}
	}
	if _u.mutation.WalletCleared() && len(_u.mutation.WalletIDs()) > 0 {
		return errors.New(`entity: clearing a required unique edge "WalletTransaction.wallet"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WalletTransactionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WalletTransactionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WalletTransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallettransaction.Table, wallettransaction.Columns, sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(wallettransaction.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(wallettransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(wallettransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(wallettransaction.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(wallettransaction.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(wallettransaction.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(wallettransaction.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Reference(); ok {
		_spec.SetField(wallettransaction.FieldReference, field.TypeString, value)
	}
	if _u.mutation.ReferenceCleared() {
		_spec.ClearField(wallettransaction.FieldReference, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(wallettransaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(wallettransaction.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(wallettransaction.FieldCreateTime, field.TypeTime, value)
	}
	if _u.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallettransaction.WalletTable,
			Columns: []string{wallettransaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallettransaction.WalletTable,
			Columns: []string{wallettransaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallettransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WalletTransactionUpdateOne is the builder for updating a single WalletTransaction entity.
type WalletTransactionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *WalletTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetType sets the "type" field.
func (_u *WalletTransactionUpdateOne) SetType(v wallettransaction.Type) *WalletTransactionUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *WalletTransactionUpdateOne) SetNillableType(v *wallettransaction.Type) *WalletTransactionUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *WalletTransactionUpdateOne) SetAmount(v float64) *WalletTransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *WalletTransactionUpdateOne) SetNillableAmount(v *float64) *WalletTransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *WalletTransactionUpdateOne) AddAmount(v float64) *WalletTransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *WalletTransactionUpdateOne) SetBalanceBefore(v float64) *WalletTransactionUpdateOne {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *WalletTransactionUpdateOne) SetNillableBalanceBefore(v *float64) *WalletTransactionUpdateOne {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *WalletTransactionUpdateOne) AddBalanceBefore(v float64) *WalletTransactionUpdateOne {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *WalletTransactionUpdateOne) SetBalanceAfter(v float64) *WalletTransactionUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *WalletTransactionUpdateOne) SetNillableBalanceAfter(v *float64) *WalletTransactionUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *WalletTransactionUpdateOne) AddBalanceAfter(v float64) *WalletTransactionUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetReference sets the "reference" field.
func (_u *WalletTransactionUpdateOne) SetReference(v string) *WalletTransactionUpdateOne {
	_u.mutation.SetReference(v)
	return _u
}

// SetNillableReference sets the "reference" field if the given value is not nil.
func (_u *WalletTransactionUpdateOne) SetNillableReference(v *string) *WalletTransactionUpdateOne {
	if v != nil {
		_u.SetReference(*v)
	}
	return _u
}

// ClearReference clears the value of the "reference" field.
func (_u *WalletTransactionUpdateOne) ClearReference() *WalletTransactionUpdateOne {
	_u.mutation.ClearReference()
	return _u
}

// SetDescription sets the "description" field.
func (_u *WalletTransactionUpdateOne) SetDescription(v string) *WalletTransactionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WalletTransactionUpdateOne) SetNillableDescription(v *string) *WalletTransactionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *WalletTransactionUpdateOne) ClearDescription() *WalletTransactionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetWalletID sets the "wallet_id" field.
func (_u *WalletTransactionUpdateOne) SetWalletID(v string) *WalletTransactionUpdateOne {
	_u.mutation.SetWalletID(v)
	return _u
}

// SetNillableWalletID sets the "wallet_id" field if the given value is not nil.
func (_u *WalletTransactionUpdateOne) SetNillableWalletID(v *string) *WalletTransactionUpdateOne {
	if v != nil {
		_u.SetWalletID(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *WalletTransactionUpdateOne) SetCreateTime(v time.Time) *WalletTransactionUpdateOne {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *WalletTransactionUpdateOne) SetNillableCreateTime(v *time.Time) *WalletTransactionUpdateOne {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (_u *WalletTransactionUpdateOne) SetWallet(v *Wallet) *WalletTransactionUpdateOne {
	return _u.SetWalletID(v.ID)
}

// Mutation returns the WalletTransactionMutation object of the builder.
func (_u *WalletTransactionUpdateOne) Mutation() *WalletTransactionMutation {
	return _u.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (_u *WalletTransactionUpdateOne) ClearWallet() *WalletTransactionUpdateOne {
	_u.mutation.ClearWallet()
	return _u
}

// Where appends a list predicates to the WalletTransactionUpdate builder.
func (_u *WalletTransactionUpdateOne) Where(ps ...predicate.WalletTransaction) *WalletTransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WalletTransactionUpdateOne) Select(field string, fields ...string) *WalletTransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WalletTransaction entity.
func (_u *WalletTransactionUpdateOne) Save(ctx context.Context) (*WalletTransaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletTransactionUpdateOne) SaveX(ctx context.Context) *WalletTransaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WalletTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletTransactionUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := wallettransaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`entity: validator failed for field "WalletTransaction.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reference(); ok {
		if err := wallettransaction.ReferenceValidator(v); err != nil {
			return &ValidationError{Name: "reference", err: fmt.Errorf(`entity: validator failed for field "WalletTransaction.reference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := wallettransaction.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`entity: validator failed for field "WalletTransaction.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletID(); ok {
		if err := wallettransaction.WalletIDValidator(v); err != nil {
			return &ValidationError{Name: "wallet_id", err: fmt.Errorf(`entity: validator failed for field "WalletTransaction.wallet_id": %w`, err)}
		}
	}
	if _u.mutation.WalletCleared() && len(_u.mutation.WalletIDs()) > 0 {
		return errors.New(`entity: clearing a required unique edge "WalletTransaction.wallet"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WalletTransactionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WalletTransactionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WalletTransactionUpdateOne) sqlSave(ctx context.Context) (_node *WalletTransaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallettransaction.Table, wallettransaction.Columns, sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entity: missing "WalletTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wallettransaction.FieldID)
		for _, f := range fields {
			if !wallettransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entity: invalid field %q for query", f)}
			}
			if f != wallettransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(wallettransaction.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(wallettransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(wallettransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(wallettransaction.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(wallettransaction.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(wallettransaction.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(wallettransaction.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Reference(); ok {
		_spec.SetField(wallettransaction.FieldReference, field.TypeString, value)
	}
	if _u.mutation.ReferenceCleared() {
		_spec.ClearField(wallettransaction.FieldReference, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(wallettransaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(wallettransaction.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(wallettransaction.FieldCreateTime, field.TypeTime, value)
	}
	if _u.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallettransaction.WalletTable,
			Columns: []string{wallettransaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallettransaction.WalletTable,
			Columns: []string{wallettransaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &WalletTransaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallettransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
